apiVersion: v1
kind: Service
metadata:
  name: negelir-api
  labels:
    app: negelir-api
spec:
  type: ClusterIP
  selector:
    app: negelir-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9091
      targetPort: 9091
