// Code generated by make config.export-go; do not edit directly.
package config

// DefaultConfig holds the default values read from common/config/defaults.yaml
// This map is informational only; actual defaults are in struct tags in config.go
var DefaultConfig = map[string]interface{}{
	"MODE": "api",
}
