"""Phase 22.6 — Comprehensive config export validation tests."""

from pathlib import Path
import re


def test_env_example_generated_matches_defaults():
    """Verify .env.example is in sync with defaults.yaml."""
    repo_root = Path(__file__).resolve().parents[1]
    env_example = repo_root / "xops" / "env" / ".env.example"
    defaults = repo_root / "common" / "config" / "defaults.yaml"
    
    assert env_example.exists(), ".env.example should exist"
    assert defaults.exists(), "defaults.yaml should exist"
    
    env_content = env_example.read_text(encoding="utf-8")
    defaults_content = defaults.read_text(encoding="utf-8")
    
    # Check that env file has header marker
    assert "GENERATED BY make config.export-env" in env_content, \
        ".env.example should have generation marker"
    
    # Extract env keys from .env.example
    env_keys = set()
    for line in env_content.split("\n"):
        if "=" in line and not line.strip().startswith("#"):
            key = line.split("=")[0].strip()
            if key:
                env_keys.add(key)
    
    # Check that at least some keys exist
    assert len(env_keys) > 0, ".env.example should contain at least one key"


def test_configuration_doc_generated_matches_defaults():
    """Verify CONFIGURATION.md registry is in sync with defaults.yaml."""
    repo_root = Path(__file__).resolve().parents[1]
    config_md = repo_root / "docs" / "design" / "CONFIGURATION.md"
    
    assert config_md.exists(), "CONFIGURATION.md should exist"
    
    content = config_md.read_text(encoding="utf-8")
    
    # Check that generated section exists
    assert "<!-- BEGIN GENERATED -->" in content, \
        "CONFIGURATION.md should have BEGIN GENERATED fence"
    assert "<!-- END GENERATED -->" in content, \
        "CONFIGURATION.md should have END GENERATED fence"
    
    # Extract generated section
    begin = content.find("<!-- BEGIN GENERATED -->")
    end = content.find("<!-- END GENERATED -->")
    generated_section = content[begin:end]
    
    # Check table structure
    assert "| Variable |" in generated_section or "|" in generated_section, \
        "Generated section should have table structure"


def test_go_config_generated_matches_defaults():
    """Verify config_defaults.go is in sync with defaults.yaml."""
    repo_root = Path(__file__).resolve().parents[1]
    go_config = repo_root / "server" / "internal" / "config" / "config_defaults.go"
    
    assert go_config.exists(), "config_defaults.go should exist"
    
    content = go_config.read_text(encoding="utf-8")
    
    # Check that it's properly formatted Go code
    assert "package config" in content, "Go file should have package declaration"
    assert "DefaultConfig" in content or "default" in content.lower(), \
        "Go file should define default config"
    assert "Code generated" in content, "Go file should have generation marker"


def test_config_exports_are_consistent():
    """Verify all three exports are consistent with each other."""
    repo_root = Path(__file__).resolve().parents[1]
    
    env_example = (repo_root / "xops" / "env" / ".env.example").read_text(encoding="utf-8")
    defaults = (repo_root / "common" / "config" / "defaults.yaml").read_text(encoding="utf-8")
    config_md = (repo_root / "docs" / "design" / "CONFIGURATION.md").read_text(encoding="utf-8")
    go_config = (repo_root / "server" / "internal" / "config" / "config_defaults.go").read_text(encoding="utf-8")
    
    # Extract key counts from each
    env_keys = len([l for l in env_example.split("\n") if "=" in l and not l.strip().startswith("#")])
    generated_section = config_md[config_md.find("<!-- BEGIN GENERATED -->"):config_md.find("<!-- END GENERATED -->")]
    doc_keys = len(re.findall(r'\| `[\w]+` \|', generated_section))
    go_keys = len(re.findall(r'"[\w]+":', go_config))
    
    # All should have similar counts (within 10% tolerance for formatting variations)
    assert env_keys > 0, "env_example should have keys"
    assert doc_keys > 0, "CONFIGURATION.md should have keys"
    assert go_keys > 0, "config_defaults.go should have keys"


if __name__ == "__main__":
    test_env_example_generated_matches_defaults()
    test_configuration_doc_generated_matches_defaults()
    test_go_config_generated_matches_defaults()
    test_config_exports_are_consistent()
    print("✅ All config export tests passed")
