"""
Phase 1 follow-up regression tests.

Goal: prevent silent drift between the runtime configuration surface
(`ai/common/config.py`, `ai/common/league_config.py`) and the documentation
surface (`.env.example`).

These tests do not require any external services. They run in any
environment where the source tree is checked out.
"""

from __future__ import annotations

import os
import pickle
import re
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
ENV_EXAMPLE = REPO_ROOT / "xops" / "env" / ".env.example"
AI_CONFIG = REPO_ROOT / "ai" / "common" / "config.py"
GO_CONFIG = REPO_ROOT / "server" / "internal" / "config" / "config.go"
DEFAULTS_YAML = REPO_ROOT / "ai" / "common" / "defaults.yaml"


def _ensure_ai_path_priority():
    """Phase 18: Force sys.path to prioritize ai/ for config imports.
    
    This ensures that imports inside ai/common/config (like common.season)
    resolve to ai/common/season, not root/common/season.
    """
    _ai_path = str(REPO_ROOT / "ai")
    if _ai_path in sys.path:
        sys.path.remove(_ai_path)
    sys.path.insert(0, _ai_path)
    # Clear any cached common modules that might have been loaded from root/
    to_remove = [k for k in list(sys.modules.keys()) if k.startswith('common')]
    for k in to_remove:
        sys.modules.pop(k, None)

# Env vars listed in .env.example but intentionally not consumed by the
# Python config layer (Go server, docker-compose, optional features).
#
# NOTE: `test_every_documented_env_var_is_consumed` filters to NEGELIR_/SCRAPE_
# prefixes, so entries here that match those prefixes will affect the test.
# Go-only and optional hardware-version keys belong here.
_PYTHON_UNUSED_ENV_KEYS = frozenset({
    # Go server-only Phase 9 knobs not in the §9.12 shared inventory
    "NEGELIR_SERVER_AUTH_LOGIN_MAX_BYTES",
    "NEGELIR_COMMON_COMPUTE_CLASS",
    "NEGELIR_SERVER_API_JWT_KEY_DIR",
    # Go server-only Phase 9 §9.2 mTLS/TLS — not in the shared inventory
    "NEGELIR_SERVER_API_MTLS_ENABLED",
    "NEGELIR_SERVER_API_TLS_DIR",
    # Go server-only telemetry knobs — not in the shared inventory
    "NEGELIR_COMMON_TELEMETRY_MAX_SERIES",
    "NEGELIR_COMMON_TELEMETRY_OTLP_ENDPOINT",
    # Phase 11 optional hardware version gates (Go-side computation)
    "NEGELIR_COMMON_CUDA_MIN_COMPUTE_CAPABILITY",
    "NEGELIR_COMMON_CUDA_MIN_VERSION",
    "NEGELIR_COMMON_CUDNN_MIN_VERSION",
    "NEGELIR_COMMON_DRIVER_NVIDIA_MIN_VERSION",
    "NEGELIR_COMMON_GLIBC_MIN_VERSION",
    "NEGELIR_COMMON_NLP_PROMOTION_RECALL_MIN",
    "NEGELIR_COMMON_OPENVINO_MIN_VERSION",
    "NEGELIR_COMMON_ROCM_MIN_VERSION",
    # Phase 10 NLP — sunset window for QA (informational, not tuning)
    "NEGELIR_SWARM_NLP_QA_ANSWER_SUNSET_ON_UTC",
    "NEGELIR_SWARM_NLP_QA_ANSWER_SUNSET_WINDOW_DAYS",
    # Legacy non-NEGELIR_ prefixes
    "DATABASE_URL",
    "REDIS_URL",
    "DB_MAX_CONNS",
    "DB_CONNECT_TIMEOUT_SEC",
    "DB_PING_TIMEOUT_SEC",
    "DB_RETRY_DELAY_SEC",
    "REDIS_RETRY_DELAY_SEC",
    "HTTP_READ_TIMEOUT_SEC",
    "HTTP_WRITE_TIMEOUT_SEC",
    "HTTP_SHUTDOWN_TIMEOUT_SEC",
    "CACHE_MATCHES_TTL_SEC",
    "CACHE_TEAMS_TTL_SEC",
    "SERVER_PORT",
})

# Env vars consumed by the Python layer but not surfaced in .env.example
# (e.g. only meaningful in CI or for ad-hoc overrides, or future phases).
_DOCS_OPTIONAL_ENV_KEYS: frozenset[str] = frozenset({
    # Phase 11 compute device configuration (hardware capability detection)
    "NEGELIR_DETERMINISTIC_KERNELS",
    "NEGELIR_HOST_PSU_CAPACITY_W",
    "NEGELIR_HOST_PSU_SAFETY_FACTOR",
    "NEGELIR_DEVICE",
    # Phase 16 Emitter (snapshot & feed generation)
    # Feed manifest configuration
    "NEGELIR_FEEDS_MANIFEST_CHANGELOG_RETENTION_DAYS",
    "NEGELIR_FEEDS_MANIFEST_SNAPSHOT_INTERVAL_MIN",
    # Miscellaneous tuning
    "NEGELIR_GLOBAL_SEED",
})

_ENV_KEY_RE = re.compile(r"^([A-Z][A-Z0-9_]*)=", re.MULTILINE)
_GETENV_RE = re.compile(r"""os\.getenv\(\s*["']([A-Z][A-Z0-9_]*)["']""")
# Matches a `# shared` marker at end of an env-line, e.g.
#   POSTGRES_HOST=postgres        # shared
_SHARED_KEY_RE = re.compile(
    r"^([A-Z][A-Z0-9_]*)=[^\n]*#\s*shared\b", re.MULTILINE
)
# Matches `env:"FOO"` struct tags in the Go config file.
_GO_ENV_TAG_RE = re.compile(r'env:"([A-Z][A-Z0-9_]*)"')


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _env_example_keys() -> set[str]:
    return set(_ENV_KEY_RE.findall(_read(ENV_EXAMPLE)))


def _python_env_keys() -> set[str]:
    keys: set[str] = set()
    for path in (AI_CONFIG,):
        keys.update(_GETENV_RE.findall(_read(path)))
    return keys


def test_env_example_exists() -> None:
    assert ENV_EXAMPLE.is_file(), f".env.example missing at {ENV_EXAMPLE}"


def test_no_duplicate_config_field_or_env_var() -> None:
    """Phase-6 audit F-3 regression gate.

    Python dataclasses silently keep the *last* declaration when two
    fields share a name, which masked a Phase-6 typo where
    ``drift_accuracy_floor`` was redeclared with a different default
    and a different env var, silently overriding the legacy
    ``ai/model/drift.py`` accuracy detector. This test walks
    ``ai/common/config.py`` for both shapes and fails on any
    collision so the next near-miss surfaces immediately.
    """
    py_text = _read(AI_CONFIG)

    # Field-name collisions (lines like `name: type = field(...)`).
    field_decl_re = re.compile(
        r"^\s{4}([a-z_][a-z0-9_]*)\s*:\s*[A-Za-z_][\w\[\], |]*\s*=\s*field\(",
        re.MULTILINE,
    )
    field_names = field_decl_re.findall(py_text)
    dup_fields = sorted(
        {n for n in field_names if field_names.count(n) > 1}
    )
    assert not dup_fields, (
        "Duplicate dataclass field declarations in ai/common/config.py "
        f"(silent shadow risk): {dup_fields}"
    )

    # Env-var collisions inside `os.getenv("KEY", "default")` calls.
    env_keys = [k for k, _v in _GETENV_DEFAULT_RE.findall(py_text)]
    dup_envs = sorted({k for k in env_keys if env_keys.count(k) > 1})
    assert not dup_envs, (
        "Duplicate `os.getenv(...)` keys in ai/common/config.py "
        f"(two fields will silently fight for the same env var): {dup_envs}"
    )


def test_every_python_env_var_is_documented() -> None:
    """Every os.getenv("FOO") in config.py must appear in .env.example."""
    docs = _env_example_keys()
    code = _python_env_keys()
    undocumented = sorted((code - docs) - _DOCS_OPTIONAL_ENV_KEYS)
    assert not undocumented, (
        "These env vars are read by Python config but not documented in "
        f".env.example: {undocumented}"
    )


def test_every_documented_env_var_is_consumed() -> None:
    """Every NEGELIR_*/SCRAPE_* key in .env.example must be read somewhere."""
    docs = _env_example_keys()
    code = _python_env_keys()
    must_be_consumed = {
        k for k in docs
        if k.startswith(("NEGELIR_", "SCRAPE_"))
    }
    orphans = sorted(must_be_consumed - code - _PYTHON_UNUSED_ENV_KEYS)
    assert not orphans, (
        "These env vars are documented in .env.example but never read by any "
        f"Python config: {orphans}"
    )


def test_ai_config_validate_passes_with_defaults() -> None:
    """`Config.validate()` must accept the shipped defaults with zero issues."""
    _ensure_ai_path_priority()
    import ai.common.config
    Config = ai.common.config.Config

    issues = Config().validate()
    assert issues == [], f"Default Config has validation issues: {issues}"


def test_ai_config_strict_validate_raises_on_bad_value(monkeypatch: pytest.MonkeyPatch) -> None:
    """Strict validation must raise on out-of-range values."""
    _ensure_ai_path_priority()
    import ai.common.config
    Config = ai.common.config.Config

    monkeypatch.setenv("NEGELIR_TRAINING_TEST_SPLIT", "1.5")
    with pytest.raises(ValueError):
        Config().validate(strict=True)


def test_league_config_pickle_roundtrip() -> None:
    """LeagueConfig must survive pickle (model bundles ride with config)."""
    _ensure_ai_path_priority()
    import ai.common.league_config
    get_league_config = ai.common.league_config.get_league_config

    cfg = get_league_config("tr_super_lig")
    restored = pickle.loads(pickle.dumps(cfg))
    assert restored.league_id == cfg.league_id
    assert restored.xgb_weight == cfg.xgb_weight
    assert restored.dixon_coles_rho == cfg.dixon_coles_rho
    assert restored.derbies == cfg.derbies


def test_no_synthetic_imports_in_production_code() -> None:
    """Phase 2 gate: no production module may import the synthetic generator."""
    forbidden = re.compile(r"\bgenerate_synthetic_dataset\b")
    offenders: list[str] = []
    for module_root in ("ai",):
        root = REPO_ROOT / module_root
        for py in root.rglob("*.py"):
            # Tests, fixtures and the test-data CLI are the allowed home.
            rel = py.relative_to(REPO_ROOT).as_posix()
            if "/tests/" in rel or rel.endswith("/tests"):
                continue
            text = py.read_text(encoding="utf-8", errors="ignore")
            if forbidden.search(text):
                offenders.append(rel)
    assert not offenders, (
        "generate_synthetic_dataset is referenced outside tests/: "
        f"{offenders}"
    )


# ── Phase 1 additions ────────────────────────────────────────────────────


def _go_env_keys() -> set[str]:
    """Env keys bound by the Go server's config layer (Phase 1.2)."""
    if not GO_CONFIG.is_file():
        return set()
    return set(_GO_ENV_TAG_RE.findall(_read(GO_CONFIG)))


def _shared_marked_keys() -> set[str]:
    return set(_SHARED_KEY_RE.findall(_read(ENV_EXAMPLE)))


def test_strict_mode_rejects_unknown_negelir_key(monkeypatch: pytest.MonkeyPatch) -> None:
    """Phase 1.1: NEGELIR_STRICT must surface unknown reserved-prefix keys."""
    _ensure_ai_path_priority()
    import ai.common.config
    Config = ai.common.config.Config

    monkeypatch.setenv("NEGELIR_COMMON_STRICT", "1")
    monkeypatch.setenv("NEGELIR_TOTALLY_BOGUS_OPTION", "boom")
    with pytest.raises(ValueError) as exc:
        Config().validate(strict=True)
    assert "NEGELIR_TOTALLY_BOGUS_OPTION" in str(exc.value)


def test_strict_mode_accepts_known_keys(monkeypatch: pytest.MonkeyPatch) -> None:
    """Strict mode must NOT trip on a legitimate, declared env key."""
    _ensure_ai_path_priority()
    import ai.common.config
    Config = ai.common.config.Config

    monkeypatch.setenv("NEGELIR_COMMON_STRICT", "1")
    monkeypatch.setenv("NEGELIR_DATASOURCE_TRAINING_TEST_SPLIT", "0.25")
    issues = Config().validate()  # explicit strict=False; env-strict still active
    # Only the unknown-key sweep should trigger; if any shows up we have a bug.
    stray = [i for i in issues if "unknown env key" in i]
    assert stray == [], f"strict mode tripped on declared key: {stray}"


def test_validate_rejects_bad_url_scheme(monkeypatch: pytest.MonkeyPatch) -> None:
    """Phase 1.1: server_url must use http/https."""
    _ensure_ai_path_priority()
    import ai.common.config
    Config = ai.common.config.Config

    monkeypatch.setenv("SERVER_URL", "ftp://nope")
    with pytest.raises(ValueError):
        Config().validate(strict=True)


def test_validate_rejects_latest_source_watcher_model_id(monkeypatch: pytest.MonkeyPatch) -> None:
    """Phase 8.4: summarizer model ids must be pinned, never *-latest."""
    _ensure_ai_path_priority()
    import ai.common.config
    Config = ai.common.config.Config

    monkeypatch.setenv("NEGELIR_SOURCE_WATCHER_SUMMARIZER_ENABLED", "true")
    monkeypatch.setenv("NEGELIR_SOURCE_WATCHER_SUMMARIZER_MODEL_ID", "gpt-4.1-latest")
    monkeypatch.setenv("NEGELIR_SOURCE_WATCHER_SUMMARIZER_PROBE_URL", "https://example.com/health")
    with pytest.raises(ValueError):
        Config().validate(strict=True)


def test_validate_rejects_summarizer_daily_cap_below_per_call(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Phase 8.4: daily token cap must be >= per-call cap."""
    _ensure_ai_path_priority()
    import ai.common.config
    Config = ai.common.config.Config

    monkeypatch.setenv("NEGELIR_SOURCE_WATCHER_SUMMARIZER_MAX_TOKENS_PER_CALL", "4096")
    monkeypatch.setenv("NEGELIR_SOURCE_WATCHER_SUMMARIZER_MAX_TOKENS_PER_DAY", "1024")
    with pytest.raises(ValueError):
        Config().validate(strict=True)


def test_shared_env_keys_are_marked() -> None:
    """Phase 1.3: any key consumed by BOTH Python and Go must carry `# shared`."""
    py = _python_env_keys()
    go = _go_env_keys()
    docs = _env_example_keys()
    shared_marker = _shared_marked_keys()

    if not go:
        pytest.skip("Go config layer not present yet")

    overlap = (py & go) & docs
    unmarked = sorted(overlap - shared_marker)
    assert not unmarked, (
        "These env vars are read by BOTH Python and Go but lack a `# shared` "
        f"marker in .env.example: {unmarked}"
    )


def test_shared_marker_only_on_actually_shared_keys() -> None:
    """A `# shared` marker must correspond to a key both layers actually read."""
    py = _python_env_keys()
    go = _go_env_keys()
    if not go:
        pytest.skip("Go config layer not present yet")
    spurious = sorted(_shared_marked_keys() - (py & go))
    assert not spurious, (
        "These keys are marked `# shared` but are not actually consumed by both "
        f"Python and Go: {spurious}"
    )


# Tunables that are NOT defaults (operational toggles, dynamic JSON overrides,
# computed values) and so are intentionally absent from defaults.yaml even
# though they're documented in .env.example. Keep tight; add only with reason.
_DEFAULTS_YAML_OPTIONAL: frozenset[str] = frozenset({
    "NEGELIR_COMMON_ALLOW_MPS",
    "NEGELIR_COMMON_ALLOW_TF32",
    "NEGELIR_COMMON_AUDIT_CHAIN_HMAC_KEY_PATH",
    "NEGELIR_COMMON_CACHE_PREDICTION_TTL_SEC",
    "NEGELIR_COMMON_CACHE_RECORD_TTL_SEC",
    "NEGELIR_COMMON_CATEGORIZER_MIN_CONF",
    "NEGELIR_COMMON_CATEGORIZER_MODEL_PATH",
    "NEGELIR_COMMON_COMPETITION_CALIBRATION_TOLERANCE_FINAL_ONLY",
    "NEGELIR_COMMON_COMPETITION_CALIBRATION_TOLERANCE_GROUP_ROUND_ROBIN",
    "NEGELIR_COMMON_COMPETITION_CALIBRATION_TOLERANCE_MULTI_STAGE_QUALIFIER",
    "NEGELIR_COMMON_COMPETITION_CALIBRATION_TOLERANCE_ROUND_ROBIN",
    "NEGELIR_COMMON_COMPETITION_CALIBRATION_TOLERANCE_SINGLE_KNOCKOUT",
    "NEGELIR_COMMON_COMPETITION_CALIBRATION_TOLERANCE_TWO_LEG_KNOCKOUT",
    "NEGELIR_COMMON_COMPUTE_ARTIFACT_CACHE_DIR",
    "NEGELIR_COMMON_COMPUTE_ARTIFACT_CACHE_MAX_MB",
    "NEGELIR_COMMON_COMPUTE_ARTIFACT_CACHE_SECRET",
    "NEGELIR_COMMON_COMPUTE_CLASS",
    "NEGELIR_COMMON_COMPUTE_PANIC_CPU",
    "NEGELIR_COMMON_COMPUTE_PANIC_DRAIN_S",
    "NEGELIR_COMMON_CPU_GOVERNOR_USE_SMT",
    "NEGELIR_COMMON_CPU_GOVERNOR_WARN_POWERSAVE",
    "NEGELIR_COMMON_CPU_LLM_BACKEND",
    "NEGELIR_COMMON_CUDA_ALLOC_CONF",
    "NEGELIR_COMMON_CUDA_MIN_COMPUTE_CAPABILITY",
    "NEGELIR_COMMON_CUDA_MIN_VERSION",
    "NEGELIR_COMMON_CUDA_MPS_ENABLED",
    "NEGELIR_COMMON_CUDA_MPS_MAX_CLIENTS",
    "NEGELIR_COMMON_CUDNN_MIN_VERSION",
    "NEGELIR_COMMON_CUP_EARLY_ROUND_CALIBRATION_MAX_DEVIATION",
    "NEGELIR_COMMON_CUP_IDENTITY_COVERAGE_MIN",
    "NEGELIR_COMMON_DEFAULT_SEASON",
    "NEGELIR_COMMON_DEVICE_PROBE_HOTPLUG_DEBOUNCE_S",
    "NEGELIR_COMMON_DEVICE_PROBE_PATH",
    "NEGELIR_COMMON_DEVICE_PROBE_TIMEOUT_S",
    "NEGELIR_COMMON_DRIVER_NVIDIA_MIN_VERSION",
    "NEGELIR_COMMON_ERA_DRIFT_TOLERANCE",
    "NEGELIR_COMMON_FATIGUE_WINDOW_H",
    "NEGELIR_COMMON_FOOTBALLDATA_HTTP_TIMEOUT",
    "NEGELIR_COMMON_GAZETTEER_COMPILE_MAX_MS",
    "NEGELIR_COMMON_GLIBC_MIN_VERSION",
    "NEGELIR_COMMON_GPU_ALLOC_DEFRAG_THRESHOLD",
    "NEGELIR_COMMON_GPU_ALLOC_FRAGMENTATION_HEADROOM",
    "NEGELIR_COMMON_GPU_ARBITER_HEDGE_ENABLED",
    "NEGELIR_COMMON_GPU_ARBITER_HEDGE_MAX_CONCURRENT",
    "NEGELIR_COMMON_GPU_ARBITER_LEASE_TTL_S",
    "NEGELIR_COMMON_GPU_ARBITER_MIN_HOLD_MS",
    "NEGELIR_COMMON_GPU_ARBITER_PREEMPT_GRACE_MS",
    "NEGELIR_COMMON_GPU_ARBITER_WEIGHTS_JSON",
    "NEGELIR_COMMON_GPU_ARBITER_WINBACK_COOLDOWN_S",
    "NEGELIR_COMMON_GPU_ENABLE_PERSISTENCE_MODE",
    "NEGELIR_COMMON_GPU_LOCK_CLOCKS",
    "NEGELIR_COMMON_GPU_REQUEST_POWER_LIMIT_W",
    "NEGELIR_COMMON_GPU_SYSTEM_RESERVE_MB",
    "NEGELIR_COMMON_HEALTH_CHECK_TIMEOUT",
    "NEGELIR_COMMON_IDENTITY_FALSE_SPLIT_MAX_PER_WEEK",
    "NEGELIR_COMMON_IDENTITY_MERGE_THRESHOLD",
    "NEGELIR_COMMON_LEAGUE_BETA_MIN_DAYS",
    "NEGELIR_COMMON_LEAGUE_CALIBRATION_MAX_DEVIATION",
    "NEGELIR_COMMON_LEAGUE_CATALOG_ACTIVE_SEASON",
    "NEGELIR_COMMON_LEAGUE_CATALOG_LOAD_MAX_MS",
    "NEGELIR_COMMON_LEAGUE_CATALOG_MAX_RSS_MB",
    "NEGELIR_COMMON_LEAGUE_DEMOTION_EVIDENCE_WINDOW_H",
    "NEGELIR_COMMON_LEAGUE_DEMOTION_MIN_DAYS",
    "NEGELIR_COMMON_LEAGUE_PRESET_TOTAL_IMPORT_MAX_MS",
    "NEGELIR_COMMON_LEAGUE_READINESS_REPORT_MAX_AGE_H",
    "NEGELIR_COMMON_LEAGUE_T2_MAX_DWELL_DAYS",
    "NEGELIR_COMMON_MACKOLIK_GROUP_ID",
    "NEGELIR_COMMON_MACKOLIK_HTTP_TIMEOUT",
    "NEGELIR_COMMON_MACKOLIK_LEAGUE_FILTER",
    "NEGELIR_COMMON_NLP_PROMOTION_RECALL_MIN",
    "NEGELIR_COMMON_NPU_MAX_ACC_DROP_PCT",
    "NEGELIR_COMMON_NPU_VENDOR",
    "NEGELIR_COMMON_OPENVINO_ASYNC_QUEUE_DEPTH",
    "NEGELIR_COMMON_OPENVINO_BLOB_CACHE_DIR",
    "NEGELIR_COMMON_OPENVINO_MIN_VERSION",
    "NEGELIR_COMMON_PROFILE",
    "NEGELIR_COMMON_REDIS_SOCKET_TIMEOUT",
    "NEGELIR_COMMON_ROCM_MIN_VERSION",
    "NEGELIR_COMMON_SCRAPE_HTTP_TIMEOUT",
    "NEGELIR_COMMON_SCRAPE_TRIGGER_TIMEOUT",
    "NEGELIR_COMMON_SERVER_FETCH_TIMEOUT",
    "NEGELIR_COMMON_TELEMETRY_DEBUG_ENABLED",
    "NEGELIR_COMMON_TELEMETRY_DEBUG_MAX_SERIES",
    "NEGELIR_COMMON_TELEMETRY_MAX_SERIES",
    "NEGELIR_COMMON_TELEMETRY_MAX_STREAM",
    "NEGELIR_COMMON_TELEMETRY_METRICS_BIND",
    "NEGELIR_COMMON_TELEMETRY_METRICS_PORT",
    "NEGELIR_COMMON_TELEMETRY_OTLP_ENDPOINT",
    "NEGELIR_DATASOURCE_DRIFT_BRIER_CEILING",
    "NEGELIR_DATASOURCE_DRIFT_FLOOR",
    "NEGELIR_DATASOURCE_DRIFT_MAX_PENDING",
    "NEGELIR_DATASOURCE_DRIFT_MAX_SETTLED",
    "NEGELIR_DATASOURCE_DRIFT_PVALUE",
    "NEGELIR_DATASOURCE_DRIFT_WINDOW",
    "NEGELIR_DATASOURCE_DRIFT_WINDOW_SIZE",
    "NEGELIR_DATASOURCE_EMITTER_CLOCK_SKEW_ALERT_MS",
    "NEGELIR_DATASOURCE_EMITTER_COMPRESSION_CODEC",
    "NEGELIR_DATASOURCE_EMITTER_COMPRESSION_LEVEL",
    "NEGELIR_DATASOURCE_EMITTER_DISK_USAGE_BLOCK_PCT",
    "NEGELIR_DATASOURCE_EMITTER_DISK_USAGE_WARN_PCT",
    "NEGELIR_DATASOURCE_EMITTER_FSYNC_BATCH_MS",
    "NEGELIR_DATASOURCE_EMITTER_FSYNC_MODE",
    "NEGELIR_DATASOURCE_EMITTER_INTRADAY_COMPACT_BYTES",
    "NEGELIR_DATASOURCE_EMITTER_MANAGEMENT_PORT",
    "NEGELIR_DATASOURCE_EMITTER_MANIFEST_MAX_AGE_MS",
    "NEGELIR_DATASOURCE_EMITTER_MANIFEST_UPDATE_INTERVAL_S",
    "NEGELIR_DATASOURCE_EMITTER_MAX_PAYLOAD_BYTES",
    "NEGELIR_DATASOURCE_EMITTER_PARQUET_MAX_PART_BYTES",
    "NEGELIR_DATASOURCE_EMITTER_PER_SOURCE_FLOOR_PCT",
    "NEGELIR_DATASOURCE_EMITTER_RECORD_CRC",
    "NEGELIR_DATASOURCE_EMITTER_SNAPSHOT_BLOOM_FPR_MAX",
    "NEGELIR_DATASOURCE_EMITTER_SNAPSHOT_COMPACTION_HOURS",
    "NEGELIR_DATASOURCE_EMITTER_SNAPSHOT_GRACE_MINUTES",
    "NEGELIR_DATASOURCE_EMITTER_SNAPSHOT_MODE",
    "NEGELIR_DATASOURCE_EMITTER_SNAPSHOT_WRITER_THREADS",
    "NEGELIR_DATASOURCE_EMITTER_SOURCE_BURST_FACTOR",
    "NEGELIR_DATASOURCE_EMITTER_SOURCE_BURST_WINDOW_S",
    "NEGELIR_DATASOURCE_EMITTER_USE_CLOCK_TAI",
    "NEGELIR_DATASOURCE_FEATURE_RANGES_JSON",
    "NEGELIR_DATASOURCE_FEED_READER_BATCH_ROWS",
    "NEGELIR_DATASOURCE_FEED_READER_DEDUP_LRU_SIZE",
    "NEGELIR_DATASOURCE_FEED_READER_PER_CALL_MAX_RESIDENT_MB",
    "NEGELIR_DATASOURCE_FEED_READER_TOMBSTONE_LRU_SIZE",
    "NEGELIR_DATASOURCE_MODEL_MAX_SIZE_MB",
    "NEGELIR_DATASOURCE_REAL_DATA_RATE_LIMIT",
    "NEGELIR_DATASOURCE_REPORT_DIR",
    "NEGELIR_DATASOURCE_SCHEDULE_DAILY_SCRAPE_HOUR",
    "NEGELIR_DATASOURCE_SCHEDULE_DAILY_SCRAPE_MINUTE",
    "NEGELIR_DATASOURCE_SCHEDULE_HEARTBEAT_MINUTES",
    "NEGELIR_DATASOURCE_SCHEDULE_OUTCOME_CHECK_HOUR",
    "NEGELIR_DATASOURCE_SCHEDULE_OUTCOME_CHECK_MINUTE",
    "NEGELIR_DATASOURCE_SCHEDULE_RETRAIN_DAY",
    "NEGELIR_DATASOURCE_SCHEDULE_RETRAIN_HOUR",
    "NEGELIR_DATASOURCE_SOURCE_FAILURE_THRESHOLD",
    "NEGELIR_DATASOURCE_SOURCE_PRIORITY",
    "NEGELIR_DATASOURCE_SOURCE_WATCHER_SUMMARIZER_ENABLED",
    "NEGELIR_DATASOURCE_SOURCE_WATCHER_SUMMARIZER_LEDGER_PATH",
    "NEGELIR_DATASOURCE_SOURCE_WATCHER_SUMMARIZER_MAX_TOKENS_PER_CALL",
    "NEGELIR_DATASOURCE_SOURCE_WATCHER_SUMMARIZER_MAX_TOKENS_PER_DAY",
    "NEGELIR_DATASOURCE_SOURCE_WATCHER_SUMMARIZER_MODEL_ID",
    "NEGELIR_DATASOURCE_SOURCE_WATCHER_SUMMARIZER_PROBE_TIMEOUT_SEC",
    "NEGELIR_DATASOURCE_SOURCE_WATCHER_SUMMARIZER_PROBE_URL",
    "NEGELIR_DATASOURCE_STALE_CONFIDENCE_PENALTY",
    "NEGELIR_DATASOURCE_STALE_THRESHOLD_SECONDS",
    "NEGELIR_DATASOURCE_THRESHOLD_HOLDOUT_ACC",
    "NEGELIR_DATASOURCE_THRESHOLD_MIN_HOLDOUT_MATCHES",
    "NEGELIR_DATASOURCE_THRESHOLD_MODEL_ACC",
    "NEGELIR_DATASOURCE_THRESHOLD_QUARANTINE_MAX",
    "NEGELIR_DATASOURCE_TRAINING_CROSS_SOURCE_AGREEMENT_MULTI",
    "NEGELIR_DATASOURCE_TRAINING_MIN_MATCHES",
    "NEGELIR_DATASOURCE_TRAINING_NOISE_PCT",
    "NEGELIR_DATASOURCE_TRAINING_SAMPLE_WEIGHTS",
    "NEGELIR_DATASOURCE_TRAINING_SEED",
    "NEGELIR_DATASOURCE_TRAINING_TEST_SPLIT",
    "NEGELIR_DATASOURCE_VERIFICATION_WINDOW_WEEKS",
    "NEGELIR_INFRA_ADVERSARIAL_CORPUS_MAX_ADDED_ROWS_PER_QUARTER",
    "NEGELIR_INFRA_CHAOS_BUS_CORRUPT_FRACTION",
    "NEGELIR_INFRA_CHAOS_COMPOSE_PROFILE",
    "NEGELIR_INFRA_CHAOS_CPU_ADVERSARIAL_TIMEOUT_S",
    "NEGELIR_INFRA_CHAOS_MTTD_BUDGET_MS",
    "NEGELIR_INFRA_CHAOS_MTTR_BUDGET_MS",
    "NEGELIR_INFRA_CHAOS_NET_ADDED_LATENCY_MS",
    "NEGELIR_INFRA_CHAOS_REDIS_FLAP_S",
    "NEGELIR_INFRA_CHAOS_TREND_REGRESSION_PCT",
    "NEGELIR_INFRA_CI_FLAKE_QUARANTINE_MAX_DAYS",
    "NEGELIR_INFRA_CI_FLAKE_RATE_THRESHOLD",
    "NEGELIR_INFRA_CI_ISOLATION_MAX_SECONDS",
    "NEGELIR_INFRA_COVERAGE_MUTATION_BUDGET_S",
    "NEGELIR_INFRA_COVERAGE_MUTATION_MIN_SCORE",
    "NEGELIR_INFRA_COVERAGE_PRAGMA_MAX_PER_MODULE",
    "NEGELIR_INFRA_DR_RESTORE_MAX_MIN",
    "NEGELIR_INFRA_FAIL_SAFE_OFFSITE_LOCK_NOT_ENFORCED",
    "NEGELIR_INFRA_FAIL_SAFE_OFFSITE_OBJECT_LOCK_DISABLED",
    "NEGELIR_INFRA_FAIL_SAFE_OFFSITE_RETENTION_NOT_APPLIED",
    "NEGELIR_INFRA_FAULT_INJECTION_ENABLED",
    "NEGELIR_INFRA_FUZZ_NIGHTLY_BUDGET_S",
    "NEGELIR_INFRA_LOAD_BASELINE_DIR",
    "NEGELIR_INFRA_LOAD_BASELINE_HARD_FLOOR_MS",
    "NEGELIR_INFRA_LOAD_BASELINE_STDEV_MULTIPLIER",
    "NEGELIR_INFRA_LOAD_REGRESSION_TOLERANCE",
    "NEGELIR_INFRA_MAINT_ACK_DETAILS_MAX_BYTES",
    "NEGELIR_INFRA_MAINT_ACK_PAYLOAD_MAX_BYTES",
    "NEGELIR_INFRA_MAINT_ACK_REASON_MAX_BYTES",
    "NEGELIR_INFRA_MAINT_ADVISORY_LOCK_MAX_HOLD_MS",
    "NEGELIR_INFRA_MAINT_AGENT_SPOOL_DIR",
    "NEGELIR_INFRA_MAINT_AGENT_SPOOL_MAX_ENTRIES",
    "NEGELIR_INFRA_MAINT_AUDIT_HMAC_KEY_B64",
    "NEGELIR_INFRA_MAINT_AUDIT_PARTITION_RETENTION_DAYS",
    "NEGELIR_INFRA_MAINT_AUDIT_PER_KIND_DETAILS_MAX_BYTES",
    "NEGELIR_INFRA_MAINT_AUDIT_RETENTION_DAYS",
    "NEGELIR_INFRA_MAINT_AUDIT_RETENTION_DAYS_OVERRIDES",
    "NEGELIR_INFRA_MAINT_AUDIT_ROW_MAX_BYTES",
    "NEGELIR_INFRA_MAINT_BACKPRESSURE_RED_ERROR_RATE_PER_S",
    "NEGELIR_INFRA_MAINT_BACKPRESSURE_RED_HEAD_AGE_S",
    "NEGELIR_INFRA_MAINT_BACKPRESSURE_RED_QUEUE_DEPTH",
    "NEGELIR_INFRA_MAINT_BACKPRESSURE_RED_STORAGE_PCT",
    "NEGELIR_INFRA_MAINT_BACKPRESSURE_YELLOW_ERROR_RATE_PER_S",
    "NEGELIR_INFRA_MAINT_BACKPRESSURE_YELLOW_FACTOR",
    "NEGELIR_INFRA_MAINT_BACKPRESSURE_YELLOW_HEAD_AGE_S",
    "NEGELIR_INFRA_MAINT_BACKPRESSURE_YELLOW_QUEUE_DEPTH",
    "NEGELIR_INFRA_MAINT_BACKPRESSURE_YELLOW_STORAGE_PCT",
    "NEGELIR_INFRA_MAINT_BACKUP_AGE_ALERT_H",
    "NEGELIR_INFRA_MAINT_BACKUP_AGE_BINARY_VERSION",
    "NEGELIR_INFRA_MAINT_BACKUP_AGE_IDENTITY_FILE",
    "NEGELIR_INFRA_MAINT_BACKUP_AGE_RECIPIENTS_FILE",
    "NEGELIR_INFRA_MAINT_BACKUP_CLOCK_STEP_BACK_ALERT_S",
    "NEGELIR_INFRA_MAINT_BACKUP_CLOCK_STEP_FORWARD_ALERT_H",
    "NEGELIR_INFRA_MAINT_BACKUP_COLD_VERIFY_CRON",
    "NEGELIR_INFRA_MAINT_BACKUP_CRON",
    "NEGELIR_INFRA_MAINT_BACKUP_DIR",
    "NEGELIR_INFRA_MAINT_BACKUP_DRY_RUN",
    "NEGELIR_INFRA_MAINT_BACKUP_DR_DRILL_ALERT_DAYS",
    "NEGELIR_INFRA_MAINT_BACKUP_DR_DRILL_CSV",
    "NEGELIR_INFRA_MAINT_BACKUP_ENCRYPTION_KEY_DIR",
    "NEGELIR_INFRA_MAINT_BACKUP_FORENSIC_MAX_BYTES",
    "NEGELIR_INFRA_MAINT_BACKUP_MAX_SKEW_H",
    "NEGELIR_INFRA_MAINT_BACKUP_MAX_VERSION_GAP",
    "NEGELIR_INFRA_MAINT_BACKUP_MIN_DR_RECIPIENTS",
    "NEGELIR_INFRA_MAINT_BACKUP_MIN_FREE_GB",
    "NEGELIR_INFRA_MAINT_BACKUP_MODEL_LINEAGE_MISSING_DEBOUNCE_H",
    "NEGELIR_INFRA_MAINT_BACKUP_MODEL_OFFSITE_RETENTION_DAYS",
    "NEGELIR_INFRA_MAINT_BACKUP_MODEL_REPRODUCIBILITY_WINDOW_H",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_ACCESS_KEY_ID",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_AGE_ALERT_H",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_BUCKET",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_BW_KBPS",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_CREDENTIAL_GRACE_DAYS",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_CREDENTIAL_MAX_AGE_DAYS",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_CRED_RELOAD_S",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_ENDPOINT",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_LIFECYCLE_MIN_DAYS",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_MULTIPART_THRESHOLD_MB",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_OBJECT_LOCK_DAYS",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_OBJECT_LOCK_REQUIRED",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_PREFLIGHT_INTERVAL_H",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_RETENTION_DAYS",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_RSYNC_DEST_PATH",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_RSYNC_HOST",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_RSYNC_SSH_KNOWN_HOSTS",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_S3_REGION",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_SECRET_ACCESS_KEY_SECRET_REF",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_STATE_MAX_AGE_H",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_TARGET",
    "NEGELIR_INFRA_MAINT_BACKUP_OFFSITE_UPLOAD_TIMEOUT_H",
    "NEGELIR_INFRA_MAINT_BACKUP_PG_CONN_LIMIT",
    "NEGELIR_INFRA_MAINT_BACKUP_PG_DSN",
    "NEGELIR_INFRA_MAINT_BACKUP_PG_DUMP_IONICE",
    "NEGELIR_INFRA_MAINT_BACKUP_PG_DUMP_NICE_LEVEL",
    "NEGELIR_INFRA_MAINT_BACKUP_PG_JOBS",
    "NEGELIR_INFRA_MAINT_BACKUP_PG_ROLE",
    "NEGELIR_INFRA_MAINT_BACKUP_PG_SECRET_MAX_AGE_DAYS",
    "NEGELIR_INFRA_MAINT_BACKUP_PII_EXCLUDED_COLUMNS",
    "NEGELIR_INFRA_MAINT_BACKUP_PRUNE_BATCH",
    "NEGELIR_INFRA_MAINT_BACKUP_PRUNE_MAX_LOCK_MS",
    "NEGELIR_INFRA_MAINT_BACKUP_PVC_SIZE_GB",
    "NEGELIR_INFRA_MAINT_BACKUP_RETENTION_DAYS",
    "NEGELIR_INFRA_MAINT_BACKUP_RETENTION_WEEKS",
    "NEGELIR_INFRA_MAINT_BACKUP_VERIFY_KEY_ROTATE_PER_DUMP",
    "NEGELIR_INFRA_MAINT_BACKUP_VERIFY_LOCK_TIMEOUT_S",
    "NEGELIR_INFRA_MAINT_BACKUP_VERIFY_MODE",
    "NEGELIR_INFRA_MAINT_BACKUP_VERIFY_ORPHAN_TTL_H",
    "NEGELIR_INFRA_MAINT_BACKUP_VERIFY_PG_IMAGE",
    "NEGELIR_INFRA_MAINT_BUS_FAIL_THRESHOLD",
    "NEGELIR_INFRA_MAINT_BUS_FAIL_WINDOW_S",
    "NEGELIR_INFRA_MAINT_BUS_SPOOL_MAX_ENTRIES",
    "NEGELIR_INFRA_MAINT_CLOCK_SUSPEND_ALERT_S",
    "NEGELIR_INFRA_MAINT_DLQ_BACKLOG_ALERT",
    "NEGELIR_INFRA_MAINT_DLQ_BACKOFF_FACTOR",
    "NEGELIR_INFRA_MAINT_DLQ_BACKOFF_LRU",
    "NEGELIR_INFRA_MAINT_DLQ_CONSUMER_BROKEN_THRESHOLD",
    "NEGELIR_INFRA_MAINT_DLQ_CONSUMER_BROKEN_WINDOW_S",
    "NEGELIR_INFRA_MAINT_DLQ_MAX_REPLAYS_PER_TICK",
    "NEGELIR_INFRA_MAINT_DLQ_PER_TOPIC_MAX_PER_MIN",
    "NEGELIR_INFRA_MAINT_DLQ_PER_TOPIC_QUOTA",
    "NEGELIR_INFRA_MAINT_DLQ_REPLAY_ALLOW_OVERRIDES",
    "NEGELIR_INFRA_MAINT_DLQ_REPLAY_BACKOFF_S",
    "NEGELIR_INFRA_MAINT_DLQ_REPLAY_RPS",
    "NEGELIR_INFRA_MAINT_DLQ_REPLAY_TOPICS_ALLOW_CSV",
    "NEGELIR_INFRA_MAINT_DLQ_STATE_MAX",
    "NEGELIR_INFRA_MAINT_DLQ_VISIT_LRU",
    "NEGELIR_INFRA_MAINT_DLQ_VISIT_MAX",
    "NEGELIR_INFRA_MAINT_LEADER_LEASE_DURATION_S",
    "NEGELIR_INFRA_MAINT_PAUSE_DEFAULT_TTL_S",
    "NEGELIR_INFRA_MAINT_PAUSE_MAX_TTL_S",
    "NEGELIR_INFRA_MAINT_PLANE_LAG_ALERT_MS",
    "NEGELIR_INFRA_MAINT_PLANE_LAG_ALERT_WINDOW_S",
    "NEGELIR_INFRA_MAINT_PLANE_RECOVERY_WINDOW_S",
    "NEGELIR_INFRA_MAINT_RUNTIME",
    "NEGELIR_INFRA_MAINT_SCALER_CLOCK_SOURCE",
    "NEGELIR_INFRA_MAINT_SCALER_COMPOSE_FILE",
    "NEGELIR_INFRA_MAINT_SCALER_CPU_BUDGET_PCT",
    "NEGELIR_INFRA_MAINT_SCALER_DECISION_WINDOW_MS",
    "NEGELIR_INFRA_MAINT_SCALER_DEFAULT_MAX_REPLICAS",
    "NEGELIR_INFRA_MAINT_SCALER_GLOBAL_MAX_REPLICAS",
    "NEGELIR_INFRA_MAINT_SCALER_HISTORY_MAX",
    "NEGELIR_INFRA_MAINT_SCALER_HYSTERESIS_GRACE",
    "NEGELIR_INFRA_MAINT_SCALER_HYSTERESIS_WINDOWS",
    "NEGELIR_INFRA_MAINT_SCALER_MANUAL_PIN_TTL_S",
    "NEGELIR_INFRA_MAINT_SCALER_MAX_CHANGES_PER_WINDOW",
    "NEGELIR_INFRA_MAINT_SCALER_MAX_REPLICAS",
    "NEGELIR_INFRA_MAINT_SCALER_MAX_REPLICAS_OVERRIDES_CSV",
    "NEGELIR_INFRA_MAINT_SCALER_MAX_STEP_PER_WINDOW",
    "NEGELIR_INFRA_MAINT_SCALER_MAX_TARGETS",
    "NEGELIR_INFRA_MAINT_SCALER_MIN_DECISION_INTERVAL_S",
    "NEGELIR_INFRA_MAINT_SCALER_MIN_REPLICAS",
    "NEGELIR_INFRA_MAINT_SCALER_NOISE_WINDOWS",
    "NEGELIR_INFRA_MAINT_SCALER_RUNTIME_HISTOGRAM_BUCKETS",
    "NEGELIR_INFRA_MAINT_SCALER_RUNTIME_TIMEOUT_S",
    "NEGELIR_INFRA_MAINT_SCALER_SCALE_DOWN_GRACE_WINDOWS",
    "NEGELIR_INFRA_MAINT_SCALER_SCALE_DOWN_QUEUE_DEPTH",
    "NEGELIR_INFRA_MAINT_SCALER_SCALE_UP_HEAD_AGE_S",
    "NEGELIR_INFRA_MAINT_SCALER_SCALE_UP_QUEUE_DEPTH",
    "NEGELIR_INFRA_MAINT_SCALER_SELF_SCALING_TARGETS",
    "NEGELIR_INFRA_MAINT_SCALER_SIGNAL_WINDOW_SAMPLES",
    "NEGELIR_INFRA_MAINT_SCALER_TARGET_LOAD_PER_REPLICA",
    "NEGELIR_INFRA_MAINT_SCALER_VRAM_HEADROOM_MB",
    "NEGELIR_INFRA_MAINT_SCALER_VRAM_PESSIMISTIC_THRESHOLD_PCT",
    "NEGELIR_INFRA_MAINT_SCALER_WARMUP_REPLICAS",
    "NEGELIR_INFRA_MAINT_SCHEMA_AUTO_APPLY_ENABLED",
    "NEGELIR_INFRA_MAINT_SCHEMA_BURST",
    "NEGELIR_INFRA_MAINT_SCHEMA_DRIFT_DEBOUNCE_S",
    "NEGELIR_INFRA_MAINT_SCHEMA_DRIFT_LRU",
    "NEGELIR_INFRA_MAINT_SCHEMA_PG_CHECK_INTERVAL_S",
    "NEGELIR_INFRA_MAINT_SCHEMA_SAMPLE_RATE_PER_S",
    "NEGELIR_INFRA_MAINT_SCHEMA_SNAPSHOT_RETENTION_DAYS",
    "NEGELIR_INFRA_MAINT_SCHEMA_VALIDATE_MAX_RPS",
    "NEGELIR_INFRA_MAINT_SEC_ALLOWLIST_PENDING_TTL_DAYS",
    "NEGELIR_INFRA_MAINT_SEC_DECIMATE_MIN_INTERVAL_S",
    "NEGELIR_INFRA_MAINT_SEC_PATTERN_PENDING_TTL_DAYS",
    "NEGELIR_INFRA_MAINT_SEC_PATTERN_PROMOTE_THRESHOLD",
    "NEGELIR_INFRA_MAINT_SEC_PATTERN_TTL_S",
    "NEGELIR_INFRA_MAINT_SEC_REQUEST_LRU",
    "NEGELIR_INFRA_MAINT_SELF_DLQ_ALERT",
    "NEGELIR_INFRA_MAINT_SELF_DLQ_GROWTH_ALERT",
    "NEGELIR_INFRA_MAINT_SELF_DLQ_THROTTLE_RECOVERY_S",
    "NEGELIR_INFRA_MAINT_SILENCE_ALERT_H",
    "NEGELIR_INFRA_MAINT_SILENCE_DEDUP_S",
    "NEGELIR_INFRA_MAINT_SILENCE_WARMUP_S",
    "NEGELIR_INFRA_MAINT_SPOOL_ENTRY_MAX_AGE_H",
    "NEGELIR_INFRA_MAINT_STORAGE_TOTAL_MAX_MB",
    "NEGELIR_INFRA_OPSCTL_ACK_TIMEOUT_MS",
    "NEGELIR_INFRA_OPSCTL_ACK_TIMEOUT_MS_LIVE_DEMO",
    "NEGELIR_INFRA_OPSCTL_AUDIT_MAX_BYTES",
    "NEGELIR_INFRA_OPSCTL_AUDIT_PATH",
    "NEGELIR_INFRA_OPSCTL_AUTHZ_FILE",
    "NEGELIR_INFRA_OPSCTL_CRITICAL_AGENTS",
    "NEGELIR_INFRA_OPSCTL_FLAME_CAPTURE_MAX_ARMED_PER_H",
    "NEGELIR_INFRA_OPSCTL_FLAME_CAPTURE_TTL_H",
    "NEGELIR_INFRA_OPSCTL_KEY_MAX_AGE_DAYS",
    "NEGELIR_INFRA_OPSCTL_KEY_PATH",
    "NEGELIR_INFRA_OPSCTL_KEY_RATE_LIMIT_PER_MIN",
    "NEGELIR_INFRA_OPSCTL_KEY_REVOCATION_GRACE_DAYS",
    "NEGELIR_INFRA_OPSCTL_KEY_REVOCATION_GRACE_S",
    "NEGELIR_INFRA_OPSCTL_KILL_SWITCH_MAX_AGE_H",
    "NEGELIR_INFRA_OPSCTL_KILL_SWITCH_PATH",
    "NEGELIR_INFRA_OPSCTL_LOCK_DIR",
    "NEGELIR_INFRA_OPSCTL_LOCK_STALE_FACTOR",
    "NEGELIR_INFRA_OPSCTL_NLP_KILL_MAX_TTL_S",
    "NEGELIR_INFRA_OPSCTL_OPERATORS_FILE",
    "NEGELIR_INFRA_OPSCTL_OPERATORS_RELOAD_S",
    "NEGELIR_INFRA_OPSCTL_REDIS_EXPECTED_USER",
    "NEGELIR_INFRA_OPSCTL_REQUIRE_SIGNATURE",
    "NEGELIR_INFRA_OPSCTL_SPOOL_ACK_MAX_WAIT_H",
    "NEGELIR_INFRA_OPSCTL_SPOOL_DIR",
    "NEGELIR_INFRA_OPSCTL_SPOOL_FLUSH_MAX_PER_RUN",
    "NEGELIR_INFRA_OPSCTL_SPOOL_MAX_ENTRIES",
    "NEGELIR_INFRA_SOAK_NIGHTLY_DURATION_S",
    "NEGELIR_INFRA_SOAK_REPORT_MAX_AGE_DAYS",
    "NEGELIR_INFRA_SOAK_RESOURCE_DRIFT_PCT",
    "NEGELIR_SERVER_API_ACCESS_TTL_S",
    "NEGELIR_SERVER_API_ADAPTIVE_ERROR_RATE_THRESHOLD",
    "NEGELIR_SERVER_API_ADAPTIVE_SHED_DURATION_S",
    "NEGELIR_SERVER_API_ADAPTIVE_SHED_FACTOR",
    "NEGELIR_SERVER_API_ALLOC_SAMPLE_RATE",
    "NEGELIR_SERVER_API_ALLOWED_MARKETS",
    "NEGELIR_SERVER_API_AUDIT_BATCH_MAX",
    "NEGELIR_SERVER_API_AUDIT_BATCH_MAX_MS",
    "NEGELIR_SERVER_API_AUDIT_CHAN_CAP",
    "NEGELIR_SERVER_API_AUDIT_SAMPLE_PCT_UNDER_PRESSURE",
    "NEGELIR_SERVER_API_BCRYPT_COST",
    "NEGELIR_SERVER_API_BENCH_TARGET_RPS",
    "NEGELIR_SERVER_API_BREAKER_FAIL_RATIO",
    "NEGELIR_SERVER_API_BREAKER_MIN_REQUESTS",
    "NEGELIR_SERVER_API_BREAKER_OPEN_S",
    "NEGELIR_SERVER_API_BREAKER_WINDOW_S",
    "NEGELIR_SERVER_API_BURST_CAPACITY",
    "NEGELIR_SERVER_API_BURST_REFILL_PER_S",
    "NEGELIR_SERVER_API_CACHE_MAX_AGE_S",
    "NEGELIR_SERVER_API_CACHE_STALE_AFTER_S",
    "NEGELIR_SERVER_API_CONSENSUS_OVERHEAD_MS",
    "NEGELIR_SERVER_API_CURSOR_TTL_S",
    "NEGELIR_SERVER_API_DEMO_BASE_URL",
    "NEGELIR_SERVER_API_DEPRECATION_WINDOW_DAYS",
    "NEGELIR_SERVER_API_FIXTURE_WINDOW_MAX_DAYS",
    "NEGELIR_SERVER_API_GO_GC_PERCENT",
    "NEGELIR_SERVER_API_GO_MEM_LIMIT_MIB",
    "NEGELIR_SERVER_API_HEDGE_AFTER_MS",
    "NEGELIR_SERVER_API_HEDGE_BUDGET_PCT",
    "NEGELIR_SERVER_API_HEDGING_ENABLED",
    "NEGELIR_SERVER_API_IDEMPOTENCY_INFLIGHT_WAIT_MS",
    "NEGELIR_SERVER_API_IDEMPOTENCY_TTL_S",
    "NEGELIR_SERVER_API_IDLE_TIMEOUT_MS",
    "NEGELIR_SERVER_API_IN_MESH_PORT",
    "NEGELIR_SERVER_API_JWT_CLOCK_SKEW_S",
    "NEGELIR_SERVER_API_JWT_KEY_DIR",
    "NEGELIR_SERVER_API_JWT_KEY_POLL_S",
    "NEGELIR_SERVER_API_JWT_RETIRED_GRACE_S",
    "NEGELIR_SERVER_API_L0_CACHE_MAX_BYTES",
    "NEGELIR_SERVER_API_L0_CACHE_MAX_ENTRIES",
    "NEGELIR_SERVER_API_L0_INVALIDATION_LAG_MAX_MS",
    "NEGELIR_SERVER_API_L0_MAX_TTL_S",
    "NEGELIR_SERVER_API_L0_REFRESH_MAX_WAIT_MS",
    "NEGELIR_SERVER_API_LOG_SAMPLE_PCT",
    "NEGELIR_SERVER_API_MAX_CONCURRENT_REQUESTS",
    "NEGELIR_SERVER_API_MTLS_ENABLED",
    "NEGELIR_SERVER_API_NEGATIVE_CACHE_S",
    "NEGELIR_SERVER_API_PG_POOL_MAX_CONNS",
    "NEGELIR_SERVER_API_PG_REPLICA_LAG_CHECK_S",
    "NEGELIR_SERVER_API_PG_REPLICA_LAG_MAX_MS",
    "NEGELIR_SERVER_API_PG_REPLICA_URL",
    "NEGELIR_SERVER_API_PPROF_DIR",
    "NEGELIR_SERVER_API_PPROF_ENABLED_DEV",
    "NEGELIR_SERVER_API_PPROF_ENABLED_PROD",
    "NEGELIR_SERVER_API_PREDICT_REQUEST_BACKLOG_HIGH",
    "NEGELIR_SERVER_API_PRIORITY_TIER_FLOOR",
    "NEGELIR_SERVER_API_PROBER_BUCKET_RPS",
    "NEGELIR_SERVER_API_READ_HEADER_TIMEOUT_MS",
    "NEGELIR_SERVER_API_READ_TIMEOUT_MS",
    "NEGELIR_SERVER_API_REDIS_BUS_POOL_SIZE",
    "NEGELIR_SERVER_API_REDIS_CACHE_POOL_SIZE",
    "NEGELIR_SERVER_API_REFRESH_REPLAY_GRACE_S",
    "NEGELIR_SERVER_API_REFRESH_TTL_S",
    "NEGELIR_SERVER_API_REGISTER_CAP_PER_SUBNET_PER_H",
    "NEGELIR_SERVER_API_REPLY_REAPER_S",
    "NEGELIR_SERVER_API_REQUEST_MAX_BYTES",
    "NEGELIR_SERVER_API_REQUEST_TIMEOUT_MS",
    "NEGELIR_SERVER_API_RESPONSE_WRITE_TIMEOUT_MS",
    "NEGELIR_SERVER_API_RETRY_BUDGET_CAPACITY",
    "NEGELIR_SERVER_API_RETRY_BUDGET_PER_S",
    "NEGELIR_SERVER_API_REVOCATION_SET_MAX",
    "NEGELIR_SERVER_API_SCHEMA_VERSION",
    "NEGELIR_SERVER_API_SELF_REGISTRATION_ENABLED",
    "NEGELIR_SERVER_API_SHUTDOWN_GRACE_S",
    "NEGELIR_SERVER_API_SLO_BURN_THRESHOLD",
    "NEGELIR_SERVER_API_SLO_BURN_WINDOW_S",
    "NEGELIR_SERVER_API_SWR_INFLIGHT_MAX",
    "NEGELIR_SERVER_API_TCP_USER_TIMEOUT_MS",
    "NEGELIR_SERVER_API_TIER_ENFORCEMENT_ENABLED",
    "NEGELIR_SERVER_API_TIME_FORMAT",
    "NEGELIR_SERVER_API_TLS_DIR",
    "NEGELIR_SERVER_API_TRANSIT_JITTER_MS",
    "NEGELIR_SERVER_API_TRUSTED_PROXIES",
    "NEGELIR_SERVER_API_WRITE_TIMEOUT_MS",
    "NEGELIR_SERVER_AUTH_LOGIN_MAX_BYTES",
    "NEGELIR_SERVER_SEC_ALERT_CRITICAL_DEBOUNCE_ENABLED",
    "NEGELIR_SERVER_SEC_ALERT_DEBOUNCER_MAX_BUCKETS",
    "NEGELIR_SERVER_SEC_ALERT_DEBOUNCE_TTL_S",
    "NEGELIR_SERVER_SEC_BURST_DEDUP_WINDOW",
    "NEGELIR_SERVER_SEC_BURST_THRESHOLD",
    "NEGELIR_SERVER_SEC_BURST_WINDOW_MS",
    "NEGELIR_SERVER_SEC_DENYLIST_ESCALATION_FACTOR",
    "NEGELIR_SERVER_SEC_DENYLIST_MAX_ENTRIES",
    "NEGELIR_SERVER_SEC_DENYLIST_TTL_S",
    "NEGELIR_SERVER_SEC_INPUT_ALLOWLIST_HMAC_KEY_MAX_AGE_DAYS",
    "NEGELIR_SERVER_SEC_INPUT_ALLOWLIST_HMAC_KEY_PATH",
    "NEGELIR_SERVER_SEC_INPUT_ALLOWLIST_RELOAD_S",
    "NEGELIR_SERVER_SEC_INPUT_BREAKER_OPEN_S",
    "NEGELIR_SERVER_SEC_INPUT_CLASSIFIER_BATCH_ENABLED",
    "NEGELIR_SERVER_SEC_INPUT_CLASSIFIER_BATCH_SIZE",
    "NEGELIR_SERVER_SEC_INPUT_CLASSIFIER_BATCH_WINDOW_MS",
    "NEGELIR_SERVER_SEC_INPUT_CLASSIFIER_DEVICE",
    "NEGELIR_SERVER_SEC_INPUT_CLASSIFIER_MAX_LATENCY_MS",
    "NEGELIR_SERVER_SEC_INPUT_CLASSIFIER_MAX_PENDING",
    "NEGELIR_SERVER_SEC_INPUT_CLASSIFIER_PATH",
    "NEGELIR_SERVER_SEC_INPUT_GATEWAY_MAX_LATENCY_MS",
    "NEGELIR_SERVER_SEC_INPUT_MAX_LEN",
    "NEGELIR_SERVER_SEC_INPUT_PATTERN_RELOAD_S",
    "NEGELIR_SERVER_SEC_PLANE_LAG_ALERT_MS",
    "NEGELIR_SERVER_SEC_PLANE_LAG_ALERT_WINDOW_S",
    "NEGELIR_SERVER_SEC_QUARANTINE_PAYLOAD_MAX_BYTES",
    "NEGELIR_SERVER_SEC_QUARANTINE_PRODUCER_QUEUE_MAX",
    "NEGELIR_SERVER_SEC_QUARANTINE_STORAGE_LAG_ALERT_MS",
    "NEGELIR_SERVER_SEC_QUARANTINE_TTL_DAYS",
    "NEGELIR_SERVER_SEC_RATE_BUCKET_IDLE_TTL_S",
    "NEGELIR_SERVER_SEC_RATE_DEFAULT_COST",
    "NEGELIR_SERVER_SEC_RATE_EVICTION_RATE_ALERT_PER_S",
    "NEGELIR_SERVER_SEC_RATE_EVICTION_RATE_WINDOW_S",
    "NEGELIR_SERVER_SEC_RATE_IPV4_PREFIX",
    "NEGELIR_SERVER_SEC_RATE_IPV6_PREFIX",
    "NEGELIR_SERVER_SEC_RATE_MAX_SUBJECTS",
    "NEGELIR_SERVER_SEC_RATE_POST_AUTH_CAPACITY",
    "NEGELIR_SERVER_SEC_RATE_POST_AUTH_REFILL_PER_S",
    "NEGELIR_SERVER_SEC_RATE_PRE_AUTH_CAPACITY",
    "NEGELIR_SERVER_SEC_RATE_PRE_AUTH_REFILL_PER_S",
    "NEGELIR_SERVER_SEC_RATE_REDIS_TIMEOUT_MS",
    "NEGELIR_SERVER_SEC_RATE_SECONDARY_CAPACITY",
    "NEGELIR_SERVER_SEC_RATE_SECONDARY_REFILL_PER_S",
    "NEGELIR_SERVER_SEC_RATE_TRUSTED_PROXIES",
    "NEGELIR_SERVER_SEC_SCRAPE_BASELINE_FLUSH_S",
    "NEGELIR_SERVER_SEC_SCRAPE_DEDUP_WINDOW",
    "NEGELIR_SERVER_SEC_SCRAPE_DOM_FINGERPRINT_MAX_NODES",
    "NEGELIR_SERVER_SEC_SCRAPE_INFLATE_RATIO_MAX",
    "NEGELIR_SERVER_SEC_SCRAPE_MAX_PENDING",
    "NEGELIR_SERVER_SEC_SCRAPE_SIMHASH_MAX_DISTANCE",
    "NEGELIR_SERVER_SEC_SCRAPE_SIMHASH_RING_SIZE",
    "NEGELIR_SERVER_SEC_SCRAPE_SIZE_DELTA_PCT",
    "NEGELIR_SERVER_SEC_SCRAPE_WARMUP_SAMPLES",
    "NEGELIR_SWARM_BACKTEST_CONCURRENCY_MAX",
    "NEGELIR_SWARM_BACKTEST_MIN_N",
    "NEGELIR_SWARM_BACKTEST_SEED",
    "NEGELIR_SWARM_BACKTEST_SWARM_FLOOR_PCT",
    "NEGELIR_SWARM_BACKTEST_WINDOW_WEEKS",
    "NEGELIR_SWARM_CONSENSUS_BRIER_WINDOW",
    "NEGELIR_SWARM_CONSENSUS_MAX_PENDING",
    "NEGELIR_SWARM_CONSENSUS_MIN_CONFIDENCE",
    "NEGELIR_SWARM_CONSENSUS_MIN_VOTERS",
    "NEGELIR_SWARM_CONSENSUS_OVERFLOW_FLAG_MIN_INTERVAL_SEC",
    "NEGELIR_SWARM_CONSENSUS_WINDOW_MS",
    "NEGELIR_SWARM_NLP_ABUSE_ACCOUNT_FARM_ACCOUNT_COUNT_MIN",
    "NEGELIR_SWARM_NLP_ABUSE_ACCOUNT_FARM_JACCARD_MIN",
    "NEGELIR_SWARM_NLP_ABUSE_DYM_ACCEPTANCE_ANOMALY_RATIO",
    "NEGELIR_SWARM_NLP_ABUSE_SHADOW_CONCENTRATION_DISTINCT_BUCKETS_MIN",
    "NEGELIR_SWARM_NLP_ABUSE_STYLE_SHIFT_KL",
    "NEGELIR_SWARM_NLP_ABUSE_WINDOW_H",
    "NEGELIR_SWARM_NLP_ACTIVE_LEARNING_QUEUE_MAX",
    "NEGELIR_SWARM_NLP_AGENT_SPOOL_DIR",
    "NEGELIR_SWARM_NLP_AGE_GATING_ENABLED",
    "NEGELIR_SWARM_NLP_ALL_CAPS_THRESHOLD",
    "NEGELIR_SWARM_NLP_ANAPHORA_EVICTION_EVENT_RATELIMIT_S",
    "NEGELIR_SWARM_NLP_ANAPHORA_LOOKBACK_SECONDS",
    "NEGELIR_SWARM_NLP_ANAPHORA_LOOKBACK_TURNS",
    "NEGELIR_SWARM_NLP_ANAPHORA_MIN_ANTECEDENT_CONFIDENCE",
    "NEGELIR_SWARM_NLP_ANSWER_CACHE_TTL_DATA_S",
    "NEGELIR_SWARM_NLP_ANSWER_CACHE_TTL_PREDICT_S",
    "NEGELIR_SWARM_NLP_ANSWER_DECORATIVE_EMOJI_ENABLED",
    "NEGELIR_SWARM_NLP_ANSWER_ENVELOPE_HMAC_REQUIRED",
    "NEGELIR_SWARM_NLP_ANSWER_FORMATS",
    "NEGELIR_SWARM_NLP_ANSWER_FORMAT_ENABLED",
    "NEGELIR_SWARM_NLP_ANSWER_SAMPLE_DAILY_CAP",
    "NEGELIR_SWARM_NLP_ANSWER_SAMPLE_INVERSE",
    "NEGELIR_SWARM_NLP_ANSWER_STREAMING",
    "NEGELIR_SWARM_NLP_ASCII_VS_RESTORED_MARGIN",
    "NEGELIR_SWARM_NLP_ASPECTUAL_STACK_MAX_DEPTH",
    "NEGELIR_SWARM_NLP_ASR_FILLER_STRIP_MAX",
    "NEGELIR_SWARM_NLP_ASSIMILATION_FOLD_ENABLED",
    "NEGELIR_SWARM_NLP_AT_MENTION_HANDLING_ENABLED",
    "NEGELIR_SWARM_NLP_AUDIT_BUNDLE_RETENTION_DAYS",
    "NEGELIR_SWARM_NLP_BACKTRACK_MAX_ATTEMPTS",
    "NEGELIR_SWARM_NLP_BENCH_LATENCY_P95_THRESHOLD_MS",
    "NEGELIR_SWARM_NLP_BOOT_BUDGET_S",
    "NEGELIR_SWARM_NLP_BOOT_CONSENSUS_SENTINEL_MATCH_ID",
    "NEGELIR_SWARM_NLP_BOOT_CONSENSUS_SMOKE_CRITICAL_S",
    "NEGELIR_SWARM_NLP_BOOT_CONSENSUS_SMOKE_TIMEOUT_S",
    "NEGELIR_SWARM_NLP_BOOT_CORPUS_TOP1_ENTITY_DRIFT_MAX_ROWS",
    "NEGELIR_SWARM_NLP_BOOT_LIVENESS_GRACE_S",
    "NEGELIR_SWARM_NLP_BUS_FAILURE_CIRCUIT_THRESHOLD",
    "NEGELIR_SWARM_NLP_CALIBRATION_HORIZON_STRICT",
    "NEGELIR_SWARM_NLP_CANARY_ACCOUNT_BUCKET_SIZE",
    "NEGELIR_SWARM_NLP_CANARY_MAX_CONFIDENCE_DRIFT",
    "NEGELIR_SWARM_NLP_CANARY_MAX_DISAGREEMENT_RATE",
    "NEGELIR_SWARM_NLP_CANARY_MIN_SHADOW_HOURS",
    "NEGELIR_SWARM_NLP_CANARY_POD",
    "NEGELIR_SWARM_NLP_CLUB_CO_TOKENS",
    "NEGELIR_SWARM_NLP_CLUB_DISAMBIGUATION_RADIUS",
    "NEGELIR_SWARM_NLP_COLLAPSE_UNICODE_SPACES",
    "NEGELIR_SWARM_NLP_COMPATIBILITY_MATRIX_PATH",
    "NEGELIR_SWARM_NLP_COMPLAINT_TRACE_DEFAULT_WINDOW_H",
    "NEGELIR_SWARM_NLP_COMPLAINT_TRACE_DIR",
    "NEGELIR_SWARM_NLP_COMPLIANCE_RELOAD_S",
    "NEGELIR_SWARM_NLP_COMPOUND_QUERY_ENABLED",
    "NEGELIR_SWARM_NLP_COMPOUND_SPLIT_ENABLED",
    "NEGELIR_SWARM_NLP_COMPOUND_SPLIT_MAX_LOOKUPS_PER_QUERY",
    "NEGELIR_SWARM_NLP_COMPOUND_SPLIT_MAX_SPLITS",
    "NEGELIR_SWARM_NLP_CONDITIONAL_MARKER_LOOKAHEAD_TOKENS",
    "NEGELIR_SWARM_NLP_CONFIDENCE_BANDS",
    "NEGELIR_SWARM_NLP_CONSENSUS_OVERHEAD_MS",
    "NEGELIR_SWARM_NLP_CONSONANT_ALTERNATION_ENABLED",
    "NEGELIR_SWARM_NLP_CONVERSATION_ENABLED_TIER_FLOOR",
    "NEGELIR_SWARM_NLP_CONVERSATION_IDLE_TTL_S",
    "NEGELIR_SWARM_NLP_CONVERSATION_INDEX_BACKEND",
    "NEGELIR_SWARM_NLP_CONVERSATION_MAX_TURNS",
    "NEGELIR_SWARM_NLP_CONVERSATION_REDIS_KEY_PREFIX",
    "NEGELIR_SWARM_NLP_CRF_MAX_RSS_MB",
    "NEGELIR_SWARM_NLP_DATE_DEFAULT_WINDOW_DAYS",
    "NEGELIR_SWARM_NLP_DECORATIVE_SET",
    "NEGELIR_SWARM_NLP_DEFAULT_ANSWER_FORMAT",
    "NEGELIR_SWARM_NLP_DEFAULT_FIXTURE_WINDOW_H",
    "NEGELIR_SWARM_NLP_DEFAULT_LOCALE",
    "NEGELIR_SWARM_NLP_DIACRITIC_HARD_CALL_MIN_FREQ",
    "NEGELIR_SWARM_NLP_DIACRITIC_MAX_RISK_PER_TOKEN",
    "NEGELIR_SWARM_NLP_DIACRITIC_SOFTG_MIN_FREQ",
    "NEGELIR_SWARM_NLP_DIACRITIC_TIE_BREAK_RATIO",
    "NEGELIR_SWARM_NLP_DIACRITIC_TIE_BREAK_RATIO_VOICE",
    "NEGELIR_SWARM_NLP_DIALECT_CLASS_MIN_RECALL",
    "NEGELIR_SWARM_NLP_DIGIT_LETTER_FOLD_ENABLED",
    "NEGELIR_SWARM_NLP_DISCLOSURE_LOCALE_FALLBACK_CHAIN",
    "NEGELIR_SWARM_NLP_DISPATCH_DEDUP_WINDOW_S",
    "NEGELIR_SWARM_NLP_DISPATCH_OVERHEAD_MS",
    "NEGELIR_SWARM_NLP_EMOJI_HINT_ENABLED",
    "NEGELIR_SWARM_NLP_EMOJI_TO_CONCEPT_ENABLED",
    "NEGELIR_SWARM_NLP_EMPTY_INPUT_ANOMALY_THRESHOLD",
    "NEGELIR_SWARM_NLP_EMPTY_INPUT_ANOMALY_WINDOW_S",
    "NEGELIR_SWARM_NLP_ENTITY_BENCH_LATENCY_P95_THRESHOLD_MS",
    "NEGELIR_SWARM_NLP_ENTITY_CRF_MODEL_MAX_SIZE_MB",
    "NEGELIR_SWARM_NLP_ENTITY_CRF_MODEL_PATH",
    "NEGELIR_SWARM_NLP_ENTITY_CRF_MODEL_SHA256",
    "NEGELIR_SWARM_NLP_ENTITY_F1_FLOOR",
    "NEGELIR_SWARM_NLP_ENTITY_KIND_PRIORITY",
    "NEGELIR_SWARM_NLP_ENTITY_LIVE_MAX_STALE_S",
    "NEGELIR_SWARM_NLP_ENTITY_POST_MATCH_MAX_STALE_S",
    "NEGELIR_SWARM_NLP_ENTITY_PRE_MATCH_MAX_STALE_S",
    "NEGELIR_SWARM_NLP_ERASE_SCAN_BATCH",
    "NEGELIR_SWARM_NLP_EVAL_CORPUS_PR_MAX_ADDED_ROWS_PER_QUARTER",
    "NEGELIR_SWARM_NLP_EVAL_CORPUS_REVIEW_REQUIRED",
    "NEGELIR_SWARM_NLP_FAIRNESS_KEY",
    "NEGELIR_SWARM_NLP_FAIRNESS_MAX_TRACKED_KEYS",
    "NEGELIR_SWARM_NLP_FASTTEXT_PIN",
    "NEGELIR_SWARM_NLP_FIXTURE_DATE_ADJACENCY_RADIUS",
    "NEGELIR_SWARM_NLP_FIXTURE_STATE_LOOKUP_TIMEOUT_MS",
    "NEGELIR_SWARM_NLP_FLAME_CAPTURE_OVERHEAD_FLOOR_PCT",
    "NEGELIR_SWARM_NLP_FOOTBALL_VOCAB_HINTS_ENABLED",
    "NEGELIR_SWARM_NLP_FORMAT_NUMBER_ROUNDING",
    "NEGELIR_SWARM_NLP_FRAGMENT_DETECTION_ENABLED",
    "NEGELIR_SWARM_NLP_GOSSIP_MAX_PODS",
    "NEGELIR_SWARM_NLP_HARMONY_TOLERANT_STRIP_ENABLED",
    "NEGELIR_SWARM_NLP_HASHTAG_HANDLING_ENABLED",
    "NEGELIR_SWARM_NLP_HOLIDAY_LOOKUP_HORIZON_DAYS",
    "NEGELIR_SWARM_NLP_HTML_UNESCAPE_ENABLED",
    "NEGELIR_SWARM_NLP_HUMANIZE",
    "NEGELIR_SWARM_NLP_HUMANIZER_BREAKER_OPEN_S",
    "NEGELIR_SWARM_NLP_HUMANIZER_BREAKER_SCOPE",
    "NEGELIR_SWARM_NLP_HUMANIZER_BUDGET_REDIS_KEY_PREFIX",
    "NEGELIR_SWARM_NLP_HUMANIZER_MAX_EDIT_RATIO",
    "NEGELIR_SWARM_NLP_HUMANIZER_MAX_LATENCY_MS",
    "NEGELIR_SWARM_NLP_HUMANIZER_MAX_NEW_TOKENS",
    "NEGELIR_SWARM_NLP_HUMANIZER_MAX_RSS_MB",
    "NEGELIR_SWARM_NLP_HUMANIZER_POD_COOLDOWN_S",
    "NEGELIR_SWARM_NLP_HUMANIZER_REPETITION_PENALTY",
    "NEGELIR_SWARM_NLP_HUMANIZER_REQUEST_RATE",
    "NEGELIR_SWARM_NLP_HUMANIZER_RESPAWN_COOLDOWN_S",
    "NEGELIR_SWARM_NLP_HUMANIZER_TEMPERATURE",
    "NEGELIR_SWARM_NLP_HUMANIZER_TOP_P",
    "NEGELIR_SWARM_NLP_HYPOTHESIS_MAX_EXAMPLES",
    "NEGELIR_SWARM_NLP_IDIOM_AMBIGUOUS_EVENT_RATELIMIT_S",
    "NEGELIR_SWARM_NLP_IDIOM_MAX_PHRASE_LEN_TOKENS",
    "NEGELIR_SWARM_NLP_IME_LAYOUT_CACHE_S",
    "NEGELIR_SWARM_NLP_INLINE_SELF_CORRECTION_ENABLED",
    "NEGELIR_SWARM_NLP_INPUT_MAX_CODEPOINTS",
    "NEGELIR_SWARM_NLP_INTAKE_WORKERS",
    "NEGELIR_SWARM_NLP_INTENT_ACCURACY_FLOOR",
    "NEGELIR_SWARM_NLP_INTENT_CACHE_MAX_ENTRIES",
    "NEGELIR_SWARM_NLP_INTENT_CACHE_TTL_S",
    "NEGELIR_SWARM_NLP_INTENT_CALIBRATION_PATH",
    "NEGELIR_SWARM_NLP_INTENT_DRIFT_WINDOW",
    "NEGELIR_SWARM_NLP_INTENT_ENUM_V4_ENABLED",
    "NEGELIR_SWARM_NLP_INTENT_MODEL_CANARY_PCT",
    "NEGELIR_SWARM_NLP_INTENT_MODEL_MAX_SIZE_MB",
    "NEGELIR_SWARM_NLP_INTENT_MODEL_PATH",
    "NEGELIR_SWARM_NLP_INTENT_MODEL_SHA256",
    "NEGELIR_SWARM_NLP_INTENT_MODEL_VERSION",
    "NEGELIR_SWARM_NLP_INTENT_RETRAIN_MAX_REGRESSION",
    "NEGELIR_SWARM_NLP_INTENT_SHADOW_MODE",
    "NEGELIR_SWARM_NLP_INTENT_TIER_MAP",
    "NEGELIR_SWARM_NLP_INTENT_TRAINING_MANIFEST_DIR",
    "NEGELIR_SWARM_NLP_INTENT_TRAIN_EVAL_MANIFEST_PATH",
    "NEGELIR_SWARM_NLP_INTENT_TRAIN_MAX_ROWS_PER_SUBJECT_BUCKET",
    "NEGELIR_SWARM_NLP_INTENT_TRAIN_SHADOW_PATH",
    "NEGELIR_SWARM_NLP_JINJA_BCC_DIR",
    "NEGELIR_SWARM_NLP_JINJA_CACHE_MAX_RSS_MB",
    "NEGELIR_SWARM_NLP_KILL_PATTERN_ARM_MAX_CONCURRENT",
    "NEGELIR_SWARM_NLP_KI_CONTEXT_DISAMBIGUATION",
    "NEGELIR_SWARM_NLP_L0_CACHE_TTL_S",
    "NEGELIR_SWARM_NLP_L1_ANSWER_CACHE_TTL_S",
    "NEGELIR_SWARM_NLP_L1_CACHE_HMAC_KEY_PATH",
    "NEGELIR_SWARM_NLP_LANG_TR_DIR",
    "NEGELIR_SWARM_NLP_LANG_TR_RELOAD_S",
    "NEGELIR_SWARM_NLP_LEAGUE_CATALOG_CONSONANT_STEMS_PATH",
    "NEGELIR_SWARM_NLP_LEXICON_CANARY_MAX_DISAGREEMENT_PCT",
    "NEGELIR_SWARM_NLP_LEXICON_CANARY_MAX_PER_FIELD_DISAGREEMENT_PCT",
    "NEGELIR_SWARM_NLP_LEXICON_COVERAGE_P50_FLOOR",
    "NEGELIR_SWARM_NLP_LEXICON_DIR",
    "NEGELIR_SWARM_NLP_LEXICON_DIVERGENCE_AUTO_QUARANTINE",
    "NEGELIR_SWARM_NLP_LEXICON_DIVERGENCE_MIN_ROUNDS",
    "NEGELIR_SWARM_NLP_LEXICON_FEED_HMAC_KEY_GRACE_S",
    "NEGELIR_SWARM_NLP_LEXICON_FEED_HMAC_KEY_PATH",
    "NEGELIR_SWARM_NLP_LEXICON_FEED_MAX_SUPPORTED_SCHEMA_VERSION",
    "NEGELIR_SWARM_NLP_LEXICON_FEED_SIGNATURE_REQUIRED",
    "NEGELIR_SWARM_NLP_LEXICON_GOSSIP_INTERVAL_S",
    "NEGELIR_SWARM_NLP_LEXICON_MAX_AGE_DAYS",
    "NEGELIR_SWARM_NLP_LEXICON_MAX_ALIASES_PER_CANONICAL",
    "NEGELIR_SWARM_NLP_LEXICON_MAX_COLLISION_LOAD",
    "NEGELIR_SWARM_NLP_LEXICON_MAX_ENTRIES_PER_FILE",
    "NEGELIR_SWARM_NLP_LEXICON_MAX_OLD_GENERATIONS",
    "NEGELIR_SWARM_NLP_LEXICON_MAX_RSS_MB",
    "NEGELIR_SWARM_NLP_LEXICON_MIN_ALIAS_APPEARANCES",
    "NEGELIR_SWARM_NLP_LEXICON_PR_MAX_ADDED_ROWS_PER_FILE",
    "NEGELIR_SWARM_NLP_LEXICON_PR_SOFT_WARN_ADDED_ROWS_PER_FILE",
    "NEGELIR_SWARM_NLP_LEXICON_REBUILD_CONCURRENCY_MAX",
    "NEGELIR_SWARM_NLP_LEXICON_REBUILD_QUEUE_MAX",
    "NEGELIR_SWARM_NLP_LEXICON_REBUILD_RSS_RESERVATION_MB",
    "NEGELIR_SWARM_NLP_LEXICON_RELOAD_S",
    "NEGELIR_SWARM_NLP_LEXICON_SOURCE",
    "NEGELIR_SWARM_NLP_LEXICON_SWAP_ATOMICITY",
    "NEGELIR_SWARM_NLP_LEXICON_SWAP_GRACE_S",
    "NEGELIR_SWARM_NLP_LEXICON_SWAP_MAX_LAG_S",
    "NEGELIR_SWARM_NLP_LOANWORD_SINGULARISATION_ENABLED",
    "NEGELIR_SWARM_NLP_LOANWORD_VARIANTS_ENABLED",
    "NEGELIR_SWARM_NLP_LOCALE_FALLBACK_CHAIN",
    "NEGELIR_SWARM_NLP_LOG_MAX_UNREDACTED_STR_LEN",
    "NEGELIR_SWARM_NLP_MATCH_ADJACENCY_RADIUS",
    "NEGELIR_SWARM_NLP_MATCH_CO_TOKENS",
    "NEGELIR_SWARM_NLP_MATCH_SEPARATOR_PATTERN",
    "NEGELIR_SWARM_NLP_MATCH_WORD_BRIDGES",
    "NEGELIR_SWARM_NLP_MAX_ANSWER_CHARS",
    "NEGELIR_SWARM_NLP_MAX_HUMANIZER_TOKENS_PER_POD_PER_HOUR",
    "NEGELIR_SWARM_NLP_MAX_HUMANIZER_TOKENS_PER_REQUEST",
    "NEGELIR_SWARM_NLP_MAX_HUMANIZER_TOKENS_PER_TENANT_PER_MIN",
    "NEGELIR_SWARM_NLP_MAX_SUBQUERIES",
    "NEGELIR_SWARM_NLP_MEGAINPUT_MIN_CHARS",
    "NEGELIR_SWARM_NLP_META_QUESTION_ROUTING_ENABLED",
    "NEGELIR_SWARM_NLP_META_QUESTION_TABLE_MAX",
    "NEGELIR_SWARM_NLP_MIN_ANSWER_CHARS",
    "NEGELIR_SWARM_NLP_MIN_INTENT_CONF",
    "NEGELIR_SWARM_NLP_MIN_TOKENS",
    "NEGELIR_SWARM_NLP_MODEL_WARM_TOUCH_ENABLED",
    "NEGELIR_SWARM_NLP_MORPH_AMBIGUOUS_MAX_PER_QUERY",
    "NEGELIR_SWARM_NLP_MORPH_CONTEXT_RADIUS",
    "NEGELIR_SWARM_NLP_MORPH_MIN_CONFIDENCE",
    "NEGELIR_SWARM_NLP_MORPH_TOPK",
    "NEGELIR_SWARM_NLP_NEGATION_ENABLED",
    "NEGELIR_SWARM_NLP_NORMALIZE_STAGE_TIMEOUT_MS",
    "NEGELIR_SWARM_NLP_NORMALIZE_TOTAL_BUDGET_P99_MS",
    "NEGELIR_SWARM_NLP_NUMERIC_REDUNDANT_RESTATEMENT_ENABLED",
    "NEGELIR_SWARM_NLP_NUMPY_PIN",
    "NEGELIR_SWARM_NLP_OCR_REPAIR_FORCE",
    "NEGELIR_SWARM_NLP_OUTPUT_GRAMMAR_VALIDATOR_KILLSWITCH_ENABLED",
    "NEGELIR_SWARM_NLP_OUTPUT_GRAMMAR_VALIDATOR_P99_MS",
    "NEGELIR_SWARM_NLP_PARTIAL_INPUT_MAX_COMPLETIONS",
    "NEGELIR_SWARM_NLP_PARTIAL_INPUT_MIN_TOKEN_LEN",
    "NEGELIR_SWARM_NLP_PASTE_MAX_NEWLINES",
    "NEGELIR_SWARM_NLP_PER_REQUEST_CPU_BUDGET_MIN_MS",
    "NEGELIR_SWARM_NLP_PER_REQUEST_CPU_BUDGET_MS",
    "NEGELIR_SWARM_NLP_PER_REQUEST_CPU_BUDGET_WITH_HUMANIZER_MS",
    "NEGELIR_SWARM_NLP_PER_REQUEST_RSS_BUDGET_MB",
    "NEGELIR_SWARM_NLP_PER_REQUEST_RSS_BUDGET_SWAP_GRACE_MB",
    "NEGELIR_SWARM_NLP_PER_TENANT_HUMANIZER_BURST",
    "NEGELIR_SWARM_NLP_PER_TENANT_HUMANIZER_REFILL_PER_S",
    "NEGELIR_SWARM_NLP_PER_TENANT_INFLIGHT_MAX",
    "NEGELIR_SWARM_NLP_PIPELINE_TIMEOUT_MS",
    "NEGELIR_SWARM_NLP_PIPELINE_VERSION",
    "NEGELIR_SWARM_NLP_POD_ID",
    "NEGELIR_SWARM_NLP_POD_RSS_MAX_MB",
    "NEGELIR_SWARM_NLP_POLITENESS_DISTRIBUTION_DRIFT_PP",
    "NEGELIR_SWARM_NLP_POLITENESS_MARKER_STRIP_ENABLED",
    "NEGELIR_SWARM_NLP_PREAMBLE_MAX_STRIP_TOKENS",
    "NEGELIR_SWARM_NLP_PREAMBLE_STRIP_ENABLED",
    "NEGELIR_SWARM_NLP_PREDICTIVE_OVERSHOOT_ENABLED",
    "NEGELIR_SWARM_NLP_PREDICTIVE_OVERSHOOT_MAX_PER_QUERY",
    "NEGELIR_SWARM_NLP_PREDICT_CITATION_HMAC_REQUIRED",
    "NEGELIR_SWARM_NLP_PREDICT_PREDICTION_ID_DETERMINISM_REQUIRED",
    "NEGELIR_SWARM_NLP_PRESSURE_HUMANIZE_OFF_S",
    "NEGELIR_SWARM_NLP_PREVIEW_DIR",
    "NEGELIR_SWARM_NLP_PREVIEW_TOKEN_BUDGET_PER_OPERATOR_PER_H",
    "NEGELIR_SWARM_NLP_PROBER_CORPUS_SIZE",
    "NEGELIR_SWARM_NLP_PROBER_HUMANIZER_DISABLED",
    "NEGELIR_SWARM_NLP_PROBER_INTERVAL_S",
    "NEGELIR_SWARM_NLP_PRODUCTIVE_PEEL_MAX_DEPTH",
    "NEGELIR_SWARM_NLP_PRODUCTIVE_PEEL_MIN_RESIDUE_RESOLUTION",
    "NEGELIR_SWARM_NLP_PROMOTION_RECALL_MIN",
    "NEGELIR_SWARM_NLP_PRO_DROP_DEFAULT_TEAM_CONFIDENCE_CAP",
    "NEGELIR_SWARM_NLP_PRO_DROP_LOOKBACK_TURNS",
    "NEGELIR_SWARM_NLP_PRO_DROP_MIN_IMPLICIT_SUBJECT_CONFIDENCE",
    "NEGELIR_SWARM_NLP_PYTHON_OVERHEAD_MB",
    "NEGELIR_SWARM_NLP_QA_ANSWER_MIN_SUPPORTED_VERSION",
    "NEGELIR_SWARM_NLP_QA_ANSWER_SUNSET_ON_UTC",
    "NEGELIR_SWARM_NLP_QA_ANSWER_SUNSET_WINDOW_DAYS",
    "NEGELIR_SWARM_NLP_QUEUE_PRESSURE_THRESHOLD",
    "NEGELIR_SWARM_NLP_QUOTATIVE_MIN_CONFIDENCE",
    "NEGELIR_SWARM_NLP_RANDOM_CASE_THRESHOLD",
    "NEGELIR_SWARM_NLP_REDUPLICATION_COLLAPSE_ENABLED",
    "NEGELIR_SWARM_NLP_RENDER_TIMEZONE",
    "NEGELIR_SWARM_NLP_REPAIR_DENSITY_P95_MAX",
    "NEGELIR_SWARM_NLP_REPEATED_QUERY_CACHE_MAX_AGE_S",
    "NEGELIR_SWARM_NLP_REPEATED_QUERY_SUMMARY_THRESHOLD",
    "NEGELIR_SWARM_NLP_REPEATED_QUERY_THRESHOLD",
    "NEGELIR_SWARM_NLP_REPEATED_QUERY_WINDOW_S",
    "NEGELIR_SWARM_NLP_REPEAT_COLLAPSE_MAX_LEN",
    "NEGELIR_SWARM_NLP_REPEAT_COLLAPSE_MIN_FREQ",
    "NEGELIR_SWARM_NLP_REQUEST_DEDUP_WINDOW_S",
    "NEGELIR_SWARM_NLP_RUNTIME_LOCALE",
    "NEGELIR_SWARM_NLP_SAFE_MODE_FALLBACK_ENABLED",
    "NEGELIR_SWARM_NLP_SEARCH_OPERATOR_DETECTION_ENABLED",
    "NEGELIR_SWARM_NLP_SHADOW_SAMPLE_RATE",
    "NEGELIR_SWARM_NLP_SHOUT_RATE_ALERT_COOLDOWN_S",
    "NEGELIR_SWARM_NLP_SHOUT_RATE_ALERT_MIN_REQUESTS",
    "NEGELIR_SWARM_NLP_SHOUT_RATE_ALERT_THRESHOLD",
    "NEGELIR_SWARM_NLP_SHOUT_RATE_ALERT_WINDOW_S",
    "NEGELIR_SWARM_NLP_SHUTDOWN_GRACE_S",
    "NEGELIR_SWARM_NLP_SINGLEFLIGHT_EVENT_MAX_AGE_S",
    "NEGELIR_SWARM_NLP_SINGLEFLIGHT_MAX_INFLIGHT",
    "NEGELIR_SWARM_NLP_SINGLEFLIGHT_SWEEP_INTERVAL_S",
    "NEGELIR_SWARM_NLP_SINGLE_EMOJI_INTENT_ENABLED",
    "NEGELIR_SWARM_NLP_SKEW_ALERT_DEBOUNCE_S",
    "NEGELIR_SWARM_NLP_SKEW_ALERT_MIN_REQUESTS",
    "NEGELIR_SWARM_NLP_SKEW_ALERT_P95",
    "NEGELIR_SWARM_NLP_SKEW_WINDOW_S",
    "NEGELIR_SWARM_NLP_SPOOL_MAX_ENTRIES",
    "NEGELIR_SWARM_NLP_SPOOL_PAYLOAD_PII_STRIP",
    "NEGELIR_SWARM_NLP_STREAMING_PROOFREAD_CHUNK_CHARS",
    "NEGELIR_SWARM_NLP_STREAMING_WRITE_TIMEOUT_MS",
    "NEGELIR_SWARM_NLP_STRIP_EMOJI",
    "NEGELIR_SWARM_NLP_STRUCTURED_INPUT_REFUSAL_ENABLED",
    "NEGELIR_SWARM_NLP_SUMMARY_AGGREGATION_TIMEOUT_MS",
    "NEGELIR_SWARM_NLP_SUMMARY_CALIBRATION_MISMATCH_POLICY",
    "NEGELIR_SWARM_NLP_SUMMARY_FANOUT_TIMEOUT_MS",
    "NEGELIR_SWARM_NLP_SUMMARY_MAX_FIXTURES",
    "NEGELIR_SWARM_NLP_SUMMARY_MAX_FIXTURES_HARD",
    "NEGELIR_SWARM_NLP_SUMMARY_MIN_FIXTURE_QUORUM",
    "NEGELIR_SWARM_NLP_SYMSPELL_MAX_RSS_MB",
    "NEGELIR_SWARM_NLP_SYSTEM_CAPABILITY_TEMPLATE_PATH",
    "NEGELIR_SWARM_NLP_TELEGRAPHIC_INFERENCE_ENABLED",
    "NEGELIR_SWARM_NLP_TELEGRAPHIC_MAX_TOKENS",
    "NEGELIR_SWARM_NLP_TELEGRAPHIC_MIN_ENTITY_CONFIDENCE",
    "NEGELIR_SWARM_NLP_TEMPLATE_FINALIZE_MIN_USER_TEXT_LEN",
    "NEGELIR_SWARM_NLP_TEMPLATE_GIT_SHA",
    "NEGELIR_SWARM_NLP_TENANT_ABUSE_QPS_THRESHOLD",
    "NEGELIR_SWARM_NLP_TENANT_ABUSE_WINDOW_S",
    "NEGELIR_SWARM_NLP_TIER_HUMANIZER_TOKENS_PER_MIN",
    "NEGELIR_SWARM_NLP_TIME_DEFAULT_PERIOD",
    "NEGELIR_SWARM_NLP_TIME_OF_DAY_SHORTHAND_ENABLED",
    "NEGELIR_SWARM_NLP_TR_NORMALIZE_SPEC_PATH",
    "NEGELIR_SWARM_NLP_TR_NORMALIZE_SPEC_REQUIRED",
    "NEGELIR_SWARM_NLP_TR_PII_REDACT_ENABLED",
    "NEGELIR_SWARM_NLP_TYPO_MAX_EDIT_DISTANCE",
    "NEGELIR_SWARM_NLP_TYPO_MAX_LOOKUPS_PER_QUERY",
    "NEGELIR_SWARM_NLP_UNRESOLVED_TOKEN_ROLLING_WINDOW_S",
    "NEGELIR_SWARM_NLP_UNRESOLVED_TOKEN_TOP_K",
    "NEGELIR_SWARM_NLP_VENUE_INFERRED_TEAM_CONFIDENCE_CAP",
    "NEGELIR_SWARM_NLP_VOICE_EVAL_ENTITY_F1_FLOOR",
    "NEGELIR_SWARM_NLP_VOICE_EVAL_INTENT_ACCURACY_FLOOR",
    "NEGELIR_SWARM_NLP_VOWEL_DROP_BEFORE_SUFFIX_ENABLED",
    "NEGELIR_SWARM_NLP_WEEKLY_EVAL_CONSECUTIVE_DROP_THRESHOLD",
    "NEGELIR_SWARM_NLP_WEEKLY_EVAL_MAX_ACCURACY_DROP",
    "NEGELIR_SWARM_NLP_WEEKLY_EVAL_SAMPLE_MAX_CHARS",
    "NEGELIR_SWARM_NLP_WEEKLY_EVAL_SAMPLE_SIZE",
    "NEGELIR_SWARM_NLP_WH_PRIOR_DRIFT_ALERT_PP",
    "NEGELIR_SWARM_NLP_WH_PRIOR_LOG_ODDS_MAX",
    "NEGELIR_SWARM_NLP_ZONEINFO_DIR",
    "NEGELIR_SWARM_PREDICTOR_MARKET_FEATURES_ENABLED",
    "NEGELIR_SWARM_PREDICTOR_MAX_VRAM_MB",
    "NEGELIR_SWARM_PREDICT_CITATION_HMAC_KEY_GRACE_S",
    "NEGELIR_SWARM_PREDICT_CITATION_HMAC_KEY_PATH",
    "NEGELIR_SWARM_PROOFREADER_AGGREGATOR_MAX_PENDING",
    "NEGELIR_SWARM_PROOFREADER_GRID_CONSISTENCY_TOL",
    "NEGELIR_SWARM_PROOFREADER_PLAUSIBILITY_MAX_PROB",
    "NEGELIR_SWARM_PROOFREADER_QUORUM_WINDOW_MS",
    "NEGELIR_SWARM_PROOFREADER_SANITY_EPS",
    "NEGELIR_SWARM_QA_ANSWER_HMAC_GRACE_S",
    "NEGELIR_SWARM_QA_ANSWER_HMAC_KEY_PATH",
    "NEGELIR_SWARM_QA_INPUT_MAX_BYTES",
    "NEGELIR_SWARM_QA_REQUEST_V1_DEDUP_WINDOW_S",
    "NEGELIR_SWARM_REACTOR_LEDGER_MAX_SIZE",
    "NEGELIR_SWARM_REACTOR_MAX_EVENT_AGE_SEC",
    "NEGELIR_SWARM_TRAINER_DEBOUNCE_SEC",
})



def test_defaults_yaml_mentions_every_documented_tunable() -> None:
    """Phase 1.1 drift gate: every NEGELIR_*/SCRAPE_* env key documented in
    .env.example must appear somewhere in defaults.yaml (as a comment tag).
    Catches the silent drift the `[~]` deferral was hiding.
    """
    if not DEFAULTS_YAML.is_file():
        pytest.skip("defaults.yaml not present")
    yml_body = _read(DEFAULTS_YAML)
    # Loose match: any UPPER_SNAKE token (≥4 chars) anywhere in the file.
    yml_mentions = set(re.findall(r"\b([A-Z][A-Z0-9_]{3,})\b", yml_body))
    must = {
        k for k in _env_example_keys()
        if k.startswith(("NEGELIR_", "SCRAPE_", "SWARM_"))
    }
    missing = sorted(must - yml_mentions - _DEFAULTS_YAML_OPTIONAL)
    assert not missing, (
        "defaults.yaml is out of sync with .env.example — these env keys are "
        "documented as tunables but never mentioned in defaults.yaml: "
        f"{missing}"
    )


def test_defaults_yaml_is_valid_yaml() -> None:
    """A regex-only drift check is fooled by a token that survives in a
    broken/merged comment line. Parse it for real to catch structural rot.
    """
    if not DEFAULTS_YAML.is_file():
        pytest.skip("defaults.yaml not present")
    yaml = pytest.importorskip("yaml")
    try:
        loaded = yaml.safe_load(_read(DEFAULTS_YAML))
    except yaml.YAMLError as exc:  # pragma: no cover - exercised on regression
        pytest.fail(f"defaults.yaml is not valid YAML: {exc}")
    assert isinstance(loaded, dict), "defaults.yaml top level must be a mapping"
    # Spot-check a few sections that landed in the Phase 1 audit so that a
    # future "merge into comment" defect can't slip past unnoticed.
    paths = loaded.get("paths") or {}
    assert "report_dir" in paths, (
        "paths.report_dir is missing — likely glued onto another comment line"
    )
    assert (loaded.get("operational") or {}).get("strict") is False, (
        "operational.strict default must be present and False"
    )


# Keys whose `os.getenv("X", "default")` fallback is allowed to differ from
# the value documented in `.env.example`. The canonical example is the host
# of a backing service: code defaults to "localhost" so a developer can run
# `python -m ...` without Docker, while `.env.example` defaults to the
# compose service name. Anything added here MUST have a one-line reason.
_VALUE_DRIFT_ALLOWED: dict[str, str] = {
    "POSTGRES_HOST": "container name vs host-dev fallback",
    "REDIS_HOST": "container name vs host-dev fallback",
    "SERVER_URL": "container hostname vs host-dev fallback",
    "POSTGRES_PASSWORD": ".env.example holds a placeholder; code default is empty",
    "NEGELIR_COMMON_STRICT": "code treats empty == off; .env.example shows '0' as a hint",
    "NEGELIR_COMMON_TELEMETRY_METRICS_PORT": "AI pipeline binds :9101 to avoid collision with Go API :9091 in single-host dev",
    "NEGELIR_COMMON_COMPUTE_ARTIFACT_CACHE_SECRET": ".env.example placeholder; code default is empty for dev",
    "NEGELIR_INFRA_LOAD_BASELINE_HARD_FLOOR_MS": "float representation: 500.0 vs 500 (semantically equivalent)",
}

# Capture `os.getenv("KEY", "literal default")` (only string-literal defaults).
_GETENV_DEFAULT_RE = re.compile(
    r"""os\.getenv\(\s*["']([A-Z][A-Z0-9_]*)["']\s*,\s*["']([^"']*)["']\s*\)"""
)


def test_python_defaults_match_env_example() -> None:
    """Phase 1 deep-audit gate: every `os.getenv("KEY", "default")` literal
    fallback in `ai/common/config.py` must equal the value documented in
    `.env.example`. Catches the silent value drift the key-only sync tests
    were blind to (e.g. SCRAPE_RATE_LIMIT_SECONDS=2 in env vs "5" in code).
    """
    py_text = _read(AI_CONFIG)
    env_text = _read(ENV_EXAMPLE)

    # Build map of KEY → documented value (strip trailing inline comment).
    env_vals: dict[str, str] = {}
    for line in env_text.splitlines():
        m = re.match(r"^([A-Z][A-Z0-9_]*)=(.*)$", line)
        if not m:
            continue
        key, raw = m.group(1), m.group(2)
        # Strip an inline `# comment` only if preceded by whitespace, so
        # in-value `#` characters survive (rare but possible in user-agents).
        env_vals[key] = re.sub(r"\s+#.*$", "", raw).strip()

    drift: list[str] = []
    for key, py_default in _GETENV_DEFAULT_RE.findall(py_text):
        if key in _VALUE_DRIFT_ALLOWED:
            continue
        env_val = env_vals.get(key)
        if env_val is None:
            continue  # already covered by key-parity test
        if py_default != env_val:
            drift.append(f"{key}: PY={py_default!r}  ENV={env_val!r}")

    assert not drift, (
        "Default-value drift between ai/common/config.py and .env.example.\n"
        "Sync the two, or add the key to `_VALUE_DRIFT_ALLOWED` with a "
        "one-line reason if the divergence is deliberate.\n  - "
        + "\n  - ".join(sorted(drift))
    )


# ── CONFIGURATION.md drift guard ─────────────────────────────────────────
#
# CONFIGURATION.md is a doctrine document, not an exhaustive key registry —
# it cites a handful of NEGELIR_*/SCRAPE_* keys as examples in prose and in
# the prefix table. The risk we guard against is *stale examples*: an env
# var gets renamed or removed but the doc still names it. That silently
# misleads readers.
#
# We do NOT require every env key to be documented in CONFIGURATION.md —
# that's the job of `.env.example` itself, which is the canonical registry.

CONFIGURATION_MD = REPO_ROOT / "docs" / "design" / "CONFIGURATION.md"
_DOC_KEY_RE = re.compile(r"\b(NEGELIR_[A-Z0-9_]+|SCRAPE_[A-Z0-9_]+)\b")


def test_configuration_md_examples_exist_in_env_example() -> None:
    """Every NEGELIR_*/SCRAPE_* key cited in CONFIGURATION.md must still exist.

    Catches stale doc examples after renames or deletions. Does *not*
    require comprehensive coverage — `.env.example` is the registry.
    """
    if not CONFIGURATION_MD.is_file():
        pytest.skip("CONFIGURATION.md not present")
    documented_examples = set(_DOC_KEY_RE.findall(_read(CONFIGURATION_MD)))
    if not documented_examples:
        pytest.skip("CONFIGURATION.md cites no concrete env keys")
    real_keys = _env_example_keys()
    stale = sorted(documented_examples - real_keys)
    assert not stale, (
        "CONFIGURATION.md cites env vars that no longer exist in "
        f".env.example: {stale}. Update the doc or restore the keys."
    )

