// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package apigen

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Ok       HealthResponseStatus = "ok"
)

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "Bearer"
)

// AcceptedResponse defines model for AcceptedResponse.
type AcceptedResponse struct {
	Status string `json:"status"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Code      string  `json:"code"`
	Error     string  `json:"error"`
	RequestId *string `json:"request_id,omitempty"`
}

// FeaturesResponse defines model for FeaturesResponse.
type FeaturesResponse struct {
	Features map[string]interface{} `json:"features"`
	MatchId  string                 `json:"match_id"`
}

// FixtureListResponse defines model for FixtureListResponse.
type FixtureListResponse struct {
	Fixtures []MatchSummary `json:"fixtures"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Db     *string              `json:"db,omitempty"`
	Redis  *string              `json:"redis,omitempty"`
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LeagueListResponse defines model for LeagueListResponse.
type LeagueListResponse struct {
	Leagues []LeagueSummary `json:"leagues"`
}

// LeagueSummary defines model for LeagueSummary.
type LeagueSummary struct {
	Country *string `json:"country,omitempty"`
	Id      string  `json:"id"`
	Name    *string `json:"name,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MatchDetailResponse defines model for MatchDetailResponse.
type MatchDetailResponse struct {
	AwayTeam *string    `json:"away_team,omitempty"`
	HomeTeam *string    `json:"home_team,omitempty"`
	Id       string     `json:"id"`
	Kickoff  *time.Time `json:"kickoff,omitempty"`
	League   *string    `json:"league,omitempty"`
	Status   *string    `json:"status,omitempty"`
}

// MatchListResponse defines model for MatchListResponse.
type MatchListResponse struct {
	Matches []MatchSummary `json:"matches"`
}

// MatchSummary defines model for MatchSummary.
type MatchSummary struct {
	AwayTeam *string    `json:"away_team,omitempty"`
	HomeTeam *string    `json:"home_team,omitempty"`
	Id       string     `json:"id"`
	Kickoff  *time.Time `json:"kickoff,omitempty"`
	League   *string    `json:"league,omitempty"`
}

// PredictionsResponse defines model for PredictionsResponse.
type PredictionsResponse struct {
	CalibrationVersion *int                              `json:"calibration_version,omitempty"`
	Markets            map[string]map[string]interface{} `json:"markets"`
	MatchId            string                            `json:"match_id"`
}

// QARequest defines model for QARequest.
type QARequest struct {
	// Query Turkish natural language query
	Query string `json:"query"`
}

// QAResponse defines model for QAResponse.
type QAResponse struct {
	Answer     string   `json:"answer"`
	Confidence *float32 `json:"confidence,omitempty"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// TeamDetailResponse defines model for TeamDetailResponse.
type TeamDetailResponse struct {
	Id     string  `json:"id"`
	League *string `json:"league,omitempty"`
	Name   *string `json:"name,omitempty"`
}

// TeamListResponse defines model for TeamListResponse.
type TeamListResponse struct {
	Teams []TeamSummary `json:"teams"`
}

// TeamSummary defines model for TeamSummary.
type TeamSummary struct {
	Id     string  `json:"id"`
	League *string `json:"league,omitempty"`
	Name   *string `json:"name,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  string                 `json:"access_token"`
	ExpiresIn    *int                   `json:"expires_in,omitempty"`
	RefreshToken *string                `json:"refresh_token,omitempty"`
	TokenType    TokenResponseTokenType `json:"token_type"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// UserProfileResponse defines model for UserProfileResponse.
type UserProfileResponse struct {
	Email openapi_types.Email `json:"email"`

	// Tier Dormant until Phase 20
	Tier   *string `json:"tier,omitempty"`
	UserId string  `json:"user_id"`
}

// DateParam defines model for DateParam.
type DateParam = openapi_types.Date

// LeagueParam defines model for LeagueParam.
type LeagueParam = string

// MatchIDPath Match identifier
type MatchIDPath = string

// TeamIDPath Team identifier
type TeamIDPath = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// Forbidden defines model for Forbidden.
type Forbidden = ErrorEnvelope

// NotFound defines model for NotFound.
type NotFound = ErrorEnvelope

// RateLimited defines model for RateLimited.
type RateLimited = ErrorEnvelope

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorEnvelope

// TooEarly defines model for TooEarly.
type TooEarly = ErrorEnvelope

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// LegacyListMatchesParams defines parameters for LegacyListMatches.
type LegacyListMatchesParams struct {
	League *LeagueParam `form:"league,omitempty" json:"league,omitempty"`
	Date   *DateParam   `form:"date,omitempty" json:"date,omitempty"`
}

// GetPredictionsParams defines parameters for GetPredictions.
type GetPredictionsParams struct {
	// Market Comma-separated market identifiers (default 1x2)
	Market *string `form:"market,omitempty" json:"market,omitempty"`
}

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody = LoginRequest

// AuthRefreshJSONRequestBody defines body for AuthRefresh for application/json ContentType.
type AuthRefreshJSONRequestBody = RefreshRequest

// AuthRegisterJSONRequestBody defines body for AuthRegister for application/json ContentType.
type AuthRegisterJSONRequestBody = RegisterRequest

// QaJSONRequestBody defines body for Qa for application/json ContentType.
type QaJSONRequestBody = QARequest
