#!/usr/bin/env python3
"""Phase 13.11 — Gazetteer auto-feed lint (refuse hand-edited gazetteer files).

Competition and Team records' aliases[] auto-feed the TR gazetteer via
`make nlp.lexicon-build`. This lint refuses any manual edits to per-league
gazetteer files that claim to be auto-generated.

Exit codes:
    0   All per-league gazetteer files are properly auto-generated
    1   Hand-edited entries detected in an auto-generated file
    2   Schema validation or parse error
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def load_gazetteer_file(path: Path) -> dict | None:
    """Load a gazetteer YAML file and return its data, or None on error."""
    try:
        import yaml
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else None
    except Exception:
        return None


def check_gazetteer_autofeed(gazetteer_path: Path) -> tuple[bool, str]:
    """Check that a gazetteer file is properly auto-generated from aliases.
    
    Returns: (is_valid, reason)
        is_valid: True if the file is valid (auto-generated by nlp.lexicon-build)
        reason: Explanation if invalid
    """
    data = load_gazetteer_file(gazetteer_path)
    if not data:
        return False, f"Invalid YAML or structure in {gazetteer_path}"
    
    # Check _meta exists
    meta = data.get("_meta", {})
    if not isinstance(meta, dict):
        return False, f"_meta must be a dict in {gazetteer_path}"
    
    # Check generator field is nlp.lexicon-build
    generator = meta.get("generator", "")
    if not generator.startswith("nlp.lexicon-build"):
        return False, f"generator must be 'nlp.lexicon-build' (found: {generator!r}) in {gazetteer_path}. Lint refuses hand-edited per-league gazetteer files."
    
    return True, ""


def main(argv: list[str] | None = None) -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Refuse hand-edited per-league gazetteer files"
    )
    parser.add_argument(
        "gazetteer_files",
        nargs="*",
        help="Gazetteer YAML files to check (default: ai/nlp/lexicon/*.tr.yaml)"
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Repository root path"
    )
    
    args = parser.parse_args(argv)
    
    if args.gazetteer_files:
        files_to_check = [Path(f) for f in args.gazetteer_files]
    else:
        # Default: check all per-league gazetteer files
        lexicon_dir = args.repo_root / "ai" / "nlp" / "lexicon"
        files_to_check = sorted([
            f for f in lexicon_dir.glob("*.tr.yaml")
            if not f.name.startswith("_")
        ])
    
    errors = []
    for gaz_file in files_to_check:
        is_valid, reason = check_gazetteer_autofeed(gaz_file)
        if not is_valid:
            errors.append(reason)
    
    if errors:
        for err_msg in errors:
            print(f"ERROR: {err_msg}", file=sys.stderr)
        return 1
    
    print(f"OK: {len(files_to_check)} gazetteer file(s) are properly auto-generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
