"""Phase 13.11 — Gazetteer auto-feed tests.

Verify that gazetteer files are auto-generated from Competition/Team aliases
and that lint refuses hand-edited entries.
"""
from __future__ import annotations

import tempfile
from pathlib import Path

import pytest
import yaml

# Import the lint module
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from xops.lint.nlp_gazetteer_autofeed import check_gazetteer_autofeed


class TestGazetteerAutofeed:
    """Test gazetteer auto-feed enforcement."""

    def test_gazetteer_marked_as_autogenerated(self):
        """Gazetteer files must declare generator: nlp.lexicon-build."""
        with tempfile.TemporaryDirectory() as tmpdir:
            gaz_path = Path(tmpdir) / "competitions.tr.yaml"
            data = {
                "_meta": {
                    "schema_version": 1,
                    "lexicon_version": "1.0.0",
                    "generated_at_utc": "2026-05-31T20:27:01Z",
                    "generator": "nlp.lexicon-build",
                },
                "entries": [
                    {
                        "canonical_id": "tr_kupasi",
                        "names": ["Türkiye Kupası"],
                        "aliases": ["kupa", "türkiye kupası"],
                    }
                ],
            }
            gaz_path.write_text(yaml.dump(data), encoding="utf-8")
            
            is_valid, reason = check_gazetteer_autofeed(gaz_path)
            assert is_valid, f"Gazetteer should be valid, but: {reason}"

    def test_gazetteer_rejects_missing_generator_field(self):
        """Gazetteer without generator field is rejected (hand-edited)."""
        with tempfile.TemporaryDirectory() as tmpdir:
            gaz_path = Path(tmpdir) / "competitions.tr.yaml"
            data = {
                "_meta": {
                    "schema_version": 1,
                    "lexicon_version": "1.0.0",
                },
                "entries": [
                    {
                        "canonical_id": "tr_kupasi",
                        "names": ["Türkiye Kupası"],
                        "aliases": ["kupa"],
                    }
                ],
            }
            gaz_path.write_text(yaml.dump(data), encoding="utf-8")
            
            is_valid, reason = check_gazetteer_autofeed(gaz_path)
            assert not is_valid
            assert "generator" in reason.lower() or "hand-edited" in reason.lower()

    def test_gazetteer_rejects_wrong_generator(self):
        """Gazetteer with wrong generator is rejected (hand-edited)."""
        with tempfile.TemporaryDirectory() as tmpdir:
            gaz_path = Path(tmpdir) / "competitions.tr.yaml"
            data = {
                "_meta": {
                    "schema_version": 1,
                    "lexicon_version": "1.0.0",
                    "generated_at_utc": "2026-05-31T20:27:01Z",
                    "generator": "manual-edit",  # Wrong generator
                },
                "entries": [
                    {
                        "canonical_id": "tr_kupasi",
                        "names": ["Türkiye Kupası"],
                        "aliases": ["kupa"],
                    }
                ],
            }
            gaz_path.write_text(yaml.dump(data), encoding="utf-8")
            
            is_valid, reason = check_gazetteer_autofeed(gaz_path)
            assert not is_valid
            assert "hand-edited" in reason.lower()

    def test_gazetteer_rejects_invalid_yaml(self):
        """Gazetteer with invalid YAML is rejected."""
        with tempfile.TemporaryDirectory() as tmpdir:
            gaz_path = Path(tmpdir) / "competitions.tr.yaml"
            gaz_path.write_text("[invalid: yaml: content:", encoding="utf-8")
            
            is_valid, reason = check_gazetteer_autofeed(gaz_path)
            assert not is_valid

    def test_gazetteer_requires_meta_dict(self):
        """Gazetteer _meta must be a dict."""
        with tempfile.TemporaryDirectory() as tmpdir:
            gaz_path = Path(tmpdir) / "competitions.tr.yaml"
            data = {
                "_meta": "not-a-dict",  # Wrong type
                "entries": [],
            }
            gaz_path.write_text(yaml.dump(data), encoding="utf-8")
            
            is_valid, reason = check_gazetteer_autofeed(gaz_path)
            assert not is_valid
            assert "dict" in reason.lower()

    def test_gazetteer_aliases_structure(self):
        """Gazetteer entries should have aliases field (from Competition/Team)."""
        # This test verifies the expected structure from Competition records
        with tempfile.TemporaryDirectory() as tmpdir:
            gaz_path = Path(tmpdir) / "competitions.tr.yaml"
            data = {
                "_meta": {
                    "schema_version": 1,
                    "lexicon_version": "1.0.0",
                    "generated_at_utc": "2026-05-31T20:27:01Z",
                    "generator": "nlp.lexicon-build",
                },
                "entries": [
                    {
                        "canonical_id": "en_premier_league",
                        "names": ["English Premier League"],
                        "aliases": ["EPL", "Premier"],  # From CompetitionPayload.aliases
                    }
                ],
            }
            gaz_path.write_text(yaml.dump(data), encoding="utf-8")
            
            is_valid, reason = check_gazetteer_autofeed(gaz_path)
            assert is_valid, f"Gazetteer with aliases from Competition records should be valid, but: {reason}"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
