#!/usr/bin/env python3
"""
Phase 22.6 — Config export generators.

Generates:
1. xops/env/.env.example from common/config/defaults.yaml + Config metadata
2. docs/design/CONFIGURATION.md registry section

Stdlib-only (per AGENTS.md §5: cross-platform, no third-party deps).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def generate_env_example() -> str:
    """Generate .env.example content from defaults.yaml."""
    repo_root = Path(__file__).resolve().parents[2]
    defaults_path = repo_root / "common" / "config" / "defaults.yaml"
    
    if not defaults_path.exists():
        raise FileNotFoundError(f"defaults.yaml not found at {defaults_path}")
    
    # Read the defaults.yaml file
    content = defaults_path.read_text(encoding="utf-8")
    
    # Extract environment variable names and defaults (simple parsing)
    lines = [
        "# GENERATED BY make config.export-env — do not edit directly",
        "# Source: common/config/defaults.yaml",
        "# Run `make config.export-env` to regenerate after editing defaults.yaml",
        "",
    ]
    
    # Extract patterns like "  key: value  # ENV_VAR_NAME"
    for line in content.split("\n"):
        line = line.rstrip()
        if not line.strip() or line.strip().startswith("#"):
            continue
        
        # Look for pattern: "key: value  # ENV_VAR"
        if ":" in line and "#" in line:
            parts = line.split("#")
            if len(parts) >= 2:
                env_var = parts[-1].strip()
                if env_var and env_var.isupper() and "_" in env_var:
                    # Extract value
                    value_part = parts[0].split(":", 1)
                    if len(value_part) > 1:
                        value = value_part[1].strip()
                        # Skip if it's a YAML section
                        if value and not value.endswith(":"):
                            lines.append(f"# {env_var}")
                            lines.append(f"{env_var}={value}")
                            lines.append("")
    
    return "\n".join(lines)


def generate_doc_registry() -> str:
    """Generate docs/design/CONFIGURATION.md registry section from defaults.yaml."""
    repo_root = Path(__file__).resolve().parents[2]
    defaults_path = repo_root / "common" / "config" / "defaults.yaml"
    
    if not defaults_path.exists():
        raise FileNotFoundError(f"defaults.yaml not found at {defaults_path}")
    
    content = defaults_path.read_text(encoding="utf-8")
    
    lines = [
        "## Exported Configuration Registry",
        "",
        "The following registry is automatically generated from `common/config/defaults.yaml`.",
        "Do not edit this section by hand; run `make config.export-doc` to regenerate.",
        "",
        "| Variable | Default | Range / values | Notes |",
        "|---|---|---|---|",
    ]
    
    # Extract key=value pairs from .env.example pattern
    for line in content.split("\n"):
        line = line.rstrip()
        if not line.strip() or line.strip().startswith("#"):
            continue
        
        if ":" in line and "#" in line:
            parts = line.split("#")
            if len(parts) >= 2:
                env_var = parts[-1].strip()
                if env_var and env_var.isupper() and "_" in env_var:
                    value_part = parts[0].split(":", 1)
                    if len(value_part) > 1:
                        value = value_part[1].strip()
                        if value and not value.endswith(":"):
                            lines.append(f"| `{env_var}` | `{value}` | — | Auto-generated |")
    
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["export-env", "export-doc", "export-go"])
    parser.add_argument("--check", action="store_true", help="Check-only mode")
    
    args = parser.parse_args(argv)
    
    try:
        if args.action == "export-env":
            content = generate_env_example()
            if not args.check:
                repo_root = Path(__file__).resolve().parents[2]
                output_path = repo_root / "xops" / "env" / ".env.example"
                output_path.write_text(content, encoding="utf-8")
                print(f"✅ Generated {output_path}", file=sys.stderr)
        elif args.action == "export-doc":
            content = generate_doc_registry()
            if not args.check:
                repo_root = Path(__file__).resolve().parents[2]
                config_md = repo_root / "docs" / "design" / "CONFIGURATION.md"
                
                # Read existing file and insert generated content between fences
                if config_md.exists():
                    existing = config_md.read_text(encoding="utf-8")
                else:
                    existing = ""
                
                # If fences don't exist, create them
                begin_fence = "<!-- BEGIN GENERATED -->"
                end_fence = "<!-- END GENERATED -->"
                
                if begin_fence in existing:
                    # Replace content between fences
                    before = existing.split(begin_fence)[0]
                    after_part = existing.split(end_fence, 1)
                    after = after_part[1] if len(after_part) > 1 else ""
                    result = before + begin_fence + "\n" + content + "\n" + end_fence + after
                else:
                    # Append new section with fences
                    result = existing.rstrip() + "\n\n" + begin_fence + "\n" + content + "\n" + end_fence + "\n"
                
                config_md.write_text(result, encoding="utf-8")
                print(f"✅ Generated {config_md}", file=sys.stderr)
        elif args.action == "export-go":
            # Generate Go config from defaults.yaml
            repo_root = Path(__file__).resolve().parents[2]
            output_path = repo_root / "server" / "internal" / "config" / "config_defaults.go"
            
            content = (
                "// Code generated by make config.export-go; do not edit directly.\n"
                "package config\n"
                "\n"
                "// DefaultConfig holds the default values read from common/config/defaults.yaml\n"
                "var DefaultConfig = map[string]interface{}{\n"
            )
            
            defaults_path = repo_root / "common" / "config" / "defaults.yaml"
            if defaults_path.exists():
                defaults_content = defaults_path.read_text(encoding="utf-8")
                for line in defaults_content.split("\n"):
                    if ":" in line and "#" in line:
                        parts = line.split("#")
                        if len(parts) >= 2:
                            env_var = parts[-1].strip()
                            if env_var and env_var.isupper() and "_" in env_var:
                                value_part = parts[0].split(":", 1)
                                if len(value_part) > 1:
                                    value = value_part[1].strip()
                                    if value and not value.endswith(":"):
                                        content += f'    "{env_var}": "{value}",\n'
            
            content += "}\n"
            
            if not args.check:
                output_path.parent.mkdir(parents=True, exist_ok=True)
                output_path.write_text(content, encoding="utf-8")
                print(f"✅ Generated {output_path}", file=sys.stderr)
        
        return 0
    except Exception as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
