"""nginx-mock vhost config generator (Phase 2.1).

Produces an nginx config tree that:
  • TLS-terminates each fake vhost with the leaf cert from `infra/mock/certs/<host>/`
  • Proxies all requests to the Go ``mocksrv`` upstream
  • Sets the ``Host`` header so mocksrv can route by source

The generator is deterministic — same inputs always produce the same
file bytes — so it's diff-friendly in git and CI-checkable.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, List

REPO_ROOT = Path(__file__).resolve().parents[2]
NGINX_DIR = REPO_ROOT / "infra" / "mock" / "nginx"

DEFAULT_HOSTS = (
    "mackolik.local",
    "nesine.local",
    "tff.local",
    "openfootball.local",
)

UPSTREAM_NAME = "mocksrv"
UPSTREAM_TARGET = "mocksrv:8090"  # docker-compose service name


# ── Templates ─────────────────────────────────────────────────


def render_main(*, hosts: Iterable[str] = DEFAULT_HOSTS) -> str:
    """Render the top-level nginx.conf (events + http + includes)."""
    vhost_includes = "\n".join(
        f"    include /etc/nginx/conf.d/vhost-{h}.conf;" for h in hosts
    )
    return (
        "# AUTOGENERATED by xops/mock/nginx.py — do not edit by hand.\n"
        "user nginx;\n"
        "worker_processes auto;\n"
        "error_log /var/log/nginx/error.log warn;\n"
        "pid /var/run/nginx.pid;\n"
        "\n"
        "events {\n"
        "    worker_connections 1024;\n"
        "}\n"
        "\n"
        "http {\n"
        "    sendfile on;\n"
        "    keepalive_timeout 65;\n"
        "    server_tokens off;\n"
        "\n"
        f"    upstream {UPSTREAM_NAME} {{\n"
        f"        server {UPSTREAM_TARGET};\n"
        "    }\n"
        "\n"
        f"{vhost_includes}\n"
        "}\n"
    )


def render_vhost(host: str) -> str:
    """Render a single TLS vhost config that proxies to mocksrv."""
    return (
        f"# AUTOGENERATED by xops/mock/nginx.py — vhost for {host}\n"
        "server {\n"
        "    listen 443 ssl;\n"
        "    http2 on;\n"
        f"    server_name {host};\n"
        "\n"
        f"    ssl_certificate     /etc/nginx/certs/{host}/chain.pem;\n"
        f"    ssl_certificate_key /etc/nginx/certs/{host}/leaf.key;\n"
        "    ssl_protocols       TLSv1.2 TLSv1.3;\n"
        "    ssl_ciphers         HIGH:!aNULL:!MD5;\n"
        "\n"
        "    access_log /var/log/nginx/access.log;\n"
        "    error_log  /var/log/nginx/error.log;\n"
        "\n"
        "    location / {\n"
        f"        proxy_pass http://{UPSTREAM_NAME};\n"
        f"        proxy_set_header Host {host};\n"
        "        proxy_set_header X-Negelir-Mock-Source $host;\n"
        "        proxy_set_header X-Real-IP $remote_addr;\n"
        "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
        "    }\n"
        "}\n"
        "\n"
        "server {\n"
        "    listen 80;\n"
        f"    server_name {host};\n"
        f"    return 301 https://$host$request_uri;\n"
        "}\n"
    )


# ── File I/O ──────────────────────────────────────────────────


def write_all(*, hosts: Iterable[str] = DEFAULT_HOSTS, root: Path = NGINX_DIR) -> List[Path]:
    """Write nginx.conf + per-vhost includes. Returns paths written."""
    root.mkdir(parents=True, exist_ok=True)
    conf_d = root / "conf.d"
    conf_d.mkdir(exist_ok=True)
    written: List[Path] = []

    main = root / "nginx.conf"
    main.write_text(render_main(hosts=hosts), encoding="utf-8")
    written.append(main)

    for host in hosts:
        path = conf_d / f"vhost-{host}.conf"
        path.write_text(render_vhost(host), encoding="utf-8")
        written.append(path)

    return written
